### ISSUE TITLE
Stavekontroll

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#107]
Kan være nyttig for innkommende bøker ("incoming-nordic" etc.). Vi kan finne en måte å gjøre stavekontroll automatisk og rapportere ord som er stavet feil.

**Comment by espso** [comment]
Si at det faktisk er stavet feil i boka, da burde vi vel la det ligge?

**Comment by josteinaj** [comment]
Jeg vet ikke helt. Vi bør iallefall ha en liste over hvilke ord som er stavet feil. Vi må nesten høre med Thomas og Elise hvordan de vil håndtere stavefeil i mottakskontrollen. Jeg tror uansette ikke vi gjør dette til noe som stopper boka i "incoming-nordic", men når vi lager en ny pipeline for mottak innen neste år så kan det hende at vi vil at boka skal stoppe.

**Comment by josteinaj** [comment]
Dette har @usama49 jobbet med. Tror ikke denne saken er relevant lenger. Lukker den.
