### ISSUE TITLE
Markering av ferdig produksjon i Quickbase

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#109]
Avhenger av: #108

Når det kommer en ny PEF i "utgave-ut/PEF", så skal denne markeres som ferdig produsert i Quickbase.

Markering av felt i Quickbase bør implementeres som en gjenbrukbar funksjon sånn at dette også kan gjøres fra andre steg i fremtiden.

Hvis boken ikke finnes i Quickbase så er det greit, da skal det ikke komme noen feilmelding. Dette vil skje for gamle bøker, og for Statped-bøker dersom disse skal inn her.

Hvis boken finnes i Quickbase, men en feil oppstår ved redigering av feltet så skal det sendes en e-post med feilmelding.

Merk at Quickbase-metadata som mellomlagres på tjeneren kun oppdateres med en times mellomrom eller noe sånt, så hvis man leser feltet fra lokalt mellomlager etter å ha endret det i Quickbase så vil det ikke gjenspeiles der.

**Comment by josteinaj** [comment]
Jeg gjenåpner denne.

@olavindergaard har du oversikt over hvor mye API-spørringer koster? Hvis vi skal skrive til QuickBase så vil det gå noen spørringer mot APIet, jeg vet ikke hvor mange...

**Comment by josteinaj** [comment]
Duplikat av #56. Beholder denne.

**Comment by josteinaj** [comment]
Relatert: #31

**Comment by olavindergaard** [comment]
> Jeg gjenåpner denne.
> 
> @olavindergaard har du oversikt over hvor mye API-spørringer koster? Hvis vi skal skrive til QuickBase så vil det gå noen spørringer mot APIet, jeg vet ikke hvor mange...

Det ser ut til at vi daglig ligger mellom 700-900 spørringer av 4300 som vi har på nåværende lisens. Jeg vil tro at vi fint vil klare både automatisk nedlasting, ferdig produsert punkt og ferdig produsert e-bok via API.
<img width="681" alt="qb api" src="https://user-images.githubusercontent.com/3963810/46721668-de703100-cc73-11e8-9260-6a13426e2f3b.PNG">

**Comment by josteinaj** [comment]
Ok, bra. Hvordan vil prisen endre seg om vi overstiger 4300? Det var det som var sykt dyrt var det ikke?

**Comment by olavindergaard** [comment]
Ned nåværende lisens får vi 100 spørringer per bruker for 300$ per bruker i året (43 brukere i dag= 4300 spørringer) =12900$ i året
Med oppgradering av lisens blir det 1000 spørringer per bruker for 480$ per bruker i året (43 brukere i dag= 43000 spørringer) = 20640$ i året.

Dersom vi trenger flere API-spørringer kan vi kjøpe tilleggspakker på 500 ekstra daglige spørringer for 600$ som nok er den greieste løsningen.

[Beskrivelse: Beskrivelse: NLB_logo]<http://www.nlb.no/>
[cid:image005.png@01D46087.66B86900]<http://www.facebook.com/pages/NLB-Norsk-lyd-og-blindeskriftbibliotek/328029534808>  [Beskrivelse: yt] <http://www.youtube.com/user/NLBwebben>

Olav Indergaard – Engineer
NLB – Norsk lyd- og blindeskriftbibliotek<http://www.nlb.no/>
Phone: (+47) 22 06 88 21 /(+47) 984 58 042
E-mail: olav.indergaard@nlb.no<mailto:olav.indergaard@nlb.no> / Mail: post@nlb.no<mailto:post@nlb.no>
Visiting address: Observatoriegata 1B, Oslo / Mail: Postboks 2764 Solli, 0204 Oslo







Fra: Jostein Austvik Jacobsen [mailto:notifications@github.com]
Sendt: 10. oktober 2018 10:43
Til: nlbdev/produksjonssystem <produksjonssystem@noreply.github.com>
Kopi: Olav Eivind Indergaard <Olav.Indergaard@nlb.no>; Mention <mention@noreply.github.com>
Emne: Re: [nlbdev/produksjonssystem] Markering av ferdig produksjon i Quickbase (#109)


Ok, bra. Hvordan vil prisen endre seg om vi overstiger 4300? Det var det som var sykt dyrt var det ikke?

**Comment by josteinaj** [comment]
Dette gjøres allerede via skriptet [QBUpdate_ProductionSys](https://github.com/nlbdev/QBUpdate_ProductionSys/). På sikt ønsker vi å erstatte Quickbase: https://github.com/nlbdev/nlbdev/issues/244. Lukker denne.
