### ISSUE TITLE
Bøker blir trigget hver dag

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#111]
Ca. 20 bøker blir trigget til steget: "EPUB til NLBPUB" på grunn av avvik i mappenavn og dc:identifier. 
```
<title>Ildvitnet</title><meta name="dc:identifier" content="DTB552812"/>

Burde vært <title>Ildvitnet</title><meta name="dc:identifier" content="552812"/>
```
Dette burde sende ut en feilmelding og kanskje stanse prosessen.

**Comment by josteinaj** [comment]
Trolig fikset i e6b56e70f7fe695ec78ae459ba6a0d7316df2e8e.

Bøker med feil mappenavn/filnavn må gies riktig navn i arkivet.

**Comment by espso** [comment]
Ok flott! Har du endret så mappenavnet blir riktig, uten å endre på dc:identifier?

**Comment by josteinaj** [comment]
Jeg la til en opprydning i "EPUB til NLBPUB" som fikser `dc:identifier` sånn som du beskrev det øverst. Den fiksede identifier'en blir brukt når den lagrer mappenavnet. (Ser forresten at jeg glemte å sørge for at den gjør det. Commitet som 795f8be7db9c7146102de31d02eb61bdb43c21cb nå.)

Men det forutsettes at mappenavnet er riktig selv om `dc:identifier` er feil, ellers måtte vi laget noen oppryddingsregler i `retry…`-trådene. Og jeg har ikke rettigheter til å endre mappenavnene av en eller annen grunn. Har du tilgang til å rename i master/EPUB og master/NLBPUB? F.eks. endre "NLB123456" til "123456" osv.? Hvis ikke så kanskje @usama49 eller @olavindergaard har tilgang.

**Comment by olavindergaard** [comment]
Jeg har gitt fulle mapperettigheter til @espso og @josteinaj , dette kan derimot ta en stund så jeg skal endre de mappenavnene som er feil manuelt.

**Comment by olavindergaard** [comment]
Jeg ser nå at disse mappene finnes fra før i master/EPUB så da sletter jeg "duplikatene" der og endrer mappenavn kun i master/NLBPUB

**Comment by josteinaj** [comment]
Supert. Takk!

Jostein

Den ons. 4. jul. 2018, 09:53 skrev Olav Indergaard <notifications@github.com

**Comment by josteinaj** [comment]
Sist jeg forsøkte å telle var det ca 50 bøker som ble trigget om og om igjen (hver 4 time?).

Har forsøkt å fikse noen av dem her:
- a27433ff1f6479e3cd47ac22fcdbc33a557510b5
- a31bb398ec5b615c741e122ea7f4bf4f8c58ad94

Håper det reduserer antallet som feiler en del, men det er noen få av bøkene som uansett må gjennomgås manuelt.

**Comment by espso** [comment]
Legger merke til at det er en del epub-til-innlesing som går på nytt hver dag. Eksempel 626626 Syria.
I utgave/inn/lydbok ligger det to forskjellige som hører til denne, (560326 og 560333). Det samme gjelder flere, som 628969 Ungarn (563082 og 562669)
Flere: 629054, 628770, 225490, 224809, 224825, 224872, 224650, 224592, 627720, 223973, 224294, 224090, 223960, 222948, 626156, 223028, 625987, 625982, 222867, 222871    

smb://128.39.251.205/tekstproduksjon/Arkiv/utgave-inn/lydbok/560326
smb://128.39.251.205/tekstproduksjon/Arkiv/utgave-inn/lydbok/560333

**Comment by josteinaj** [comment]
Denne ble løst for et par uker siden eller noe sånt. Lager en egen sak for epub-til-innlesing.

**Comment by espso** [comment]
Skjer igjen på epub til innlesing og PEF. Må undersøkes nærmere

**Comment by espso** [comment]
Lukker igjen, denne gangen relatert til #165. Sluttet å autotrigge etter at filen var tilbake
