### ISSUE TITLE
Alt blir trigget etter midlertidig mangel på tilgang til mountet disk

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#119]
Alle bøker blir trigget som "nye" hvis produksjonssystemet ikke har tilgang til mappene en periode, og deretter får tilgang igjen. Kan være greit å få fikset. Skjedde lørdag 07.07. ca. 13:30 etter restart av servere. 

```python
Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 629, in _monitor_book_events_thread
    expect=self._md5[f]["shallow"] if f in self._md5 else None)
  File "/opt/produksjonssystem/produksjonssystem/core/utils/filesystem.py", line 96, in path_md5
    stat = os.stat(filePath)
OSError: [Errno 112] Host is down: '/media/archive/utgave-klargjort/e-bok/355908/EPUB/images/557308-001.jpg'
```

**Comment by olavindergaard** [comment]
Dette skjedde igjen i går (31.07) også. Jeg tror det kan være greit å få fikset dette (setter Pri-2 her foreløpig).

**Comment by espso** [comment]
Hvis det fortsatt er lang kø kan det fikses midlertidig ved å ta en restart

**Comment by espso** [comment]
Ja skal prøve på det

**Comment by olavindergaard** [comment]
En utrolig teit workaround på dette problemet kan være å legge inn automatisk oppdatering av produksjonssystemet i oppstartsskriptet på SRVNLBEPUB. Dette vil forhindre at alle produksjoner trigges som nye selv om vi ikke fikser bug.

**Comment by espso** [comment]
Har greid å reprodusere det nå ved mount av lokal mappe som windows share, skal se om jeg får fikset det.

**Comment by espso** [comment]
Ser ut som bøkene som ligger urørte blir trigget som "modified" og lagt i køen når systemet mister kontakt med serveren. I stop() legges alle bøker tilbake i køen som ikke er autotriggered. Kan enten prøve å legge til modified i tillegg til autotriggered, eller se nærmere på hvorfor de blir trigget som modified. @josteinaj hva tenker du?

**Comment by josteinaj** [comment]
Hmm. Hva om vi bare tømmer køen både når den mister kontakt med mappen, og når den får tilbake kontakten? Litt synd å miste køen men det bør vel ikke skje alt for ofte?

**Comment by espso** [comment]
Ja det er kanskje det greieste

**Comment by olavindergaard** [comment]
Tømming av kø er vel en akseptabel løsning da sitasjonen som regel kun vil oppstå en gang i måneden (Microsoft patch Tuesday).

**Comment by josteinaj** [comment]
Når på dagen skjer Microsoft patch Tuesday?

**Comment by olavindergaard** [comment]
Tirsdager klokken 20:00 rulles oppdateringer ut fra Microsoft, men Nasjonalbiblioteket har nok en egen rutine for patching. Jeg skal sjekke med dem.

**Comment by espso** [comment]
Ser ut som trigget er fiksa ved at køen tømmes når mounten forsvinner. Problemet er at noen blir trigget som nye når mounten kommer tilbake

**Comment by josteinaj** [comment]
Mulig jeg fant feilen. `shouldHandleBooks` settes til `True` før `_md5`-mellomlageret er oppdatert. Da starter den antageligvis å overvåke mappen samtidig som den bygger opp `_md5`, og da tror jeg bøker kan dukke opp som "nye".

https://github.com/nlbdev/produksjonssystem/compare/4a068176af808e56cf6fc272b4ee0bb5010cdb83...669e51253ed55a97ff0c40e9568f19f78a71d244

**Comment by josteinaj** [comment]
Niks. Funka ikke det jeg gjorde.

**Comment by josteinaj** [comment]
Tror ikke dette et problem nå for tiden. Vi har gjort noen tilpasninger i løpet av 2019 for å håndtere dette mener jeg. Blant annet lagring av MD5-sjekksummer når systemet slåes av og på.
