### ISSUE TITLE
Lenker til katalogposter blir feil for tidsskrifter

### ISSUE THREAD

**Issue by olavindergaard** [nlbdev/produksjonssystem#120]
Katalogreferansen for tidsskrifter hentes fra den forrige valideringen som ble gjort i produksjonssystemet. Tipper tilvekstnumner må trunkeres til seks tegn (det blir feil uansett, men mer riktig enn slik det er nå).

**Comment by josteinaj** [comment]
Katalogreferanse for tidsskrift er første seks siffer fra dc:identifier,
eventuelt fra filnavn. Tidligere valideringer skal ikke ha noe å si.

Jostein

Den ons. 1. aug. 2018, 14:37 skrev Olav Indergaard <notifications@github.com

**Comment by olavindergaard** [comment]
OK. Da ser det ut til å være en ny feil som har oppstått. Lukker denne og feilsøker videre.
