### ISSUE TITLE
Fikse e-postlenker sånn at de virker i Outlook igjen

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#121]
Antageligvis har det skjedd noe når NB byttet e-posttjeneren vår, eventuelt kan det ha vært noe med oppsettet NB gjorde av alle Windows-installasjonene våre. Litt uklart hvorfor lenkene i e-postene har sluttet å fungere nå.

Vi må finne ut hva slags lenker som fungerer fra e-poster i Outlook, og endre de i produksjonssystemet tilsvarende. Kanskje vi må bytte til DNS-navn istedenfor IP, eller stasjonsbokstaven i Windows. Dette må isåfall konfigureres i produksjonssystemet på en eller annen måte siden det ikke går an å finne stasjonsbokstaven automatisk (kanskje DNS-navn kan finnes automatisk). Det beste er kanskje å konfigurere dette i `produksjonssystem.yml`.

**Comment by espso** [comment]
Kanskje vi kan fikse sånn at de også funker på linux? Hvis det ikke er for kronglete

**Comment by josteinaj** [comment]
Ja det hadde vært veldig fint om det fungerte på Linux også. Sist jeg prøvde så fikk jeg det ikke til ordentlig.

Skal man bruke valide URLer for å lenke til delte Windows-mapper så skal man bruke `smb://x.x.x.x/...`, men det virker ikke så bra i Windows. Jeg tror det virker i Linux, men noen type linker blir filtrert/"fikset" av Exchange tror jeg, så det er ikke sikkert at det vil komme fram i webmail som en `smb://`-lenke. `smb://` fungerer heldigvis i Slack, og jeg har lest at det skal fungere i Windows også, men når jeg prøvde hos Kari nettopp så virket det ikke fra Slack. Det fungerer i Linux fra Slack for meg iallefall.

I e-postene som skal åpnes fra Windows bruker vi nå formen `\\x.x.x.x\...`. Dette virker ikke i Linux. Og nå virker det ikke i Windows lenger heller.

Kanskje det har noe med autentisering å gjøre?

Hvis vi kan lage en lenke i e-postene som fungerer i Linux men ikke i Windows så kan vi legge til et lite ikon etter hver lenke med en lenke som fungerer i Linux: 🐧 (unicode-pingvin).

Her er noen varianter jeg kommer på som vi kan prøve:

- `smb://ip/…`
- `smb://dns/…`
- `smb://dns.nlb.no/…`
- `\\ip\…`
- `\\dns\…`
- `\\dns.nlb.no\…`
- `file:///stasjonsbokstav:/…`
- `file:///stasjonsbokstav/…`
- `stasjonsbokstav:/…`
- `file:///\\ip\…`
- `file:///\\dns\…`
- `file:///\\dns.nlb.no\…`

Lenker til delte Windows-mapper kommer i webmail som `<a href="file:///\\dns\…">`.

Jeg får ikke opp kildekoden/originalen/råteksten i Outlooks webmail men hvis jeg videresender til GMail og sjekker kildekoden derifra så står det det samme (`file:///\\dns\…`). Så det er antageligvis den mest lovende formen. Jeg tror vi kan finne DNS-navn basert på IP fra python også.

**Comment by olavindergaard** [comment]
I windows er det stasjonsbokstav (file:///Y:/) som gjelder for smb, så path bør være

- file:///Y:/Arkiv/master/EPUB/563092/

Egentlig er dette et Windows-problem så vi kan høre med NB om de kan distribuere en registry-endring til våre klienter (som beskrevet [her](https://superuser.com/questions/1064142/opening-smb-links-on-windows?answertab=oldest#tab-top)

**Comment by josteinaj** [comment]
Standard-syntaks for delte Windows-mapper er `smb://ip/Sharename/archive/master/EPUB...`,

(eventuelt med hostname definert i DNS istedenfor IP). Men `smb://`-protokollen støttes

ikke i Windows. Det skal visstnok gå an å legge til støtte for dette i Windows ved

å redigere registeret, men det virker litt upraktisk å skulle gjøre dette på alle

NLBs PCer, og er uansett ikke nødvendigvis en løsning på problemet vårt her.

 

Etter å ha testet en del forskjellige syntakser så ser det ut til at disse fungerer:

 

```

\\ip/Sharename/archive/master/EPUB/...

\\ip\Sharename\archive\master\EPUB\...

file://ip/Sharename/archive/master/EPUB/...

file://ip\Sharename\archive\master\EPUB\...

file:\\ip/Sharename/archive/master/EPUB/...

file:\\ip\Sharename\archive\master\EPUB\...

file:///\\ip/Sharename/archive/master/EPUB/...

file:///\\ip\Sharename\archive\master\EPUB\...

file://\\ip/Sharename/archive/master/EPUB/...

file://\\ip\Sharename\archive\master\EPUB\...

stasjonsbokstav:/master/EPUB/...

stasjonsbokstav:\master\EPUB\...

\\stasjonsbokstav:/master/EPUB/...

\\stasjonsbokstav:\master\EPUB\...

file:stasjonsbokstav:/master/EPUB/...

file:stasjonsbokstav:\master\EPUB\...

file:/stasjonsbokstav:/master/EPUB/...

file:/stasjonsbokstav:\master\EPUB\...

file://stasjonsbokstav:/master/EPUB/...

file://stasjonsbokstav:\master\EPUB\...

file:///stasjonsbokstav:/master/EPUB/...

file:///stasjonsbokstav:\master\EPUB\...

file:\\stasjonsbokstav:/master/EPUB/...

file:\\stasjonsbokstav:\master\EPUB\...

file:/\\stasjonsbokstav:/master/EPUB/...

file:/\\stasjonsbokstav:\master\EPUB\...

file:///\\stasjonsbokstav:/master/EPUB/...

file:///\\stasjonsbokstav:\master\EPUB\...

file://\\stasjonsbokstav:/master/EPUB/...

file://\\stasjonsbokstav:\master\EPUB\...

```

 

Det går ikke an å bruke hostname lenger. Men det har vi uansett ikke brukt i produksjonssystemet tidligere.

 

Hvis man limer inn `\\ip\Sharename\Path` i en ny e-post i Outlook, så gjør Outlook følgende:

- legger på `file:///` på starten

- gjør om Sharename og Path til små bokstaver

 

Altså:

 

```

file:///\\ip\sharename\path

```

I produksjonssystemet sender vi i dag ut `\\ip\Sharename\Path`.

Vi kan godt legge på `file:///`, men det skal egentlig ikke ha noe å si.

På min maskin fungerer `\\ip\Sharename`, men altså ikke på f.eks. Kari sin maskin.

 

Jeg bruker (antageligvis som de fleste andre andre her på huset):

- Windows 10 Enterprise 2015 LTSB

- Outlook 2013 (Standard)

@usama49 @olavindergaard: fungerer lenkene i e-postene dere får fra produksjonssystemet i Outlook hos dere eller gjelder det bare Kari?

**Comment by josteinaj** [comment]
Det fungerer ikke for Mari heller.

**Comment by josteinaj** [comment]
@usama49 sjekket hos @KariRudjord og det var et problem med rettigheter og det nye domenet vårt. Det virker nå.
