### ISSUE TITLE
Ikke overskriv master/NLBPUB

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#122]
Hvis det skjer en endring i master/EPUB så vil vi ikke overskrive master/NLBPUB, i tilfelle det har skjedd en manuell endring i master/NLBPUB...

**Comment by josteinaj** [comment]
`master/NLBPUB` er mappen hvor vi kan gjøre manuelle endringer. Hvis vi gjør manuell endringer så vil vi være sikre på at de ikke overskrives. Se også #124.

**Comment by espso** [comment]
Har laget en implementasjon av dette, der overwrite blir send som optional parameter i run og deretter i filesystem.storebook(). Skal boken under touches eller ikke?

Også lurer jeg på om vi skal implementere det nå eller vente til ny linje blir satt i drift, vet ikke helt hva praksisen er i forhold til endringer av bøker, men siden DTbook linjene kommer før nlbpub kan det kanskje være at noen vil endre noe i master/epub manuelt?

**Comment by josteinaj** [comment]
Boken under skal ikke `touch`es. Vi trenger ikke lage alt nedover i systemet på nytt.

Ja `master/EPUB` er på en måte der vi kan gjøre manuelle endringer i dag, men i praksis gjør vi vel ingen endringer der. Jeg synes godt du kan implementere det nå.

Det bør kanskje gå en e-post selv om den ikke overskrives, sånn at man vet hvorfor det ikke skjer noe (akkurat som for bøker som ikke skal produseres).
