### ISSUE TITLE
Bedre tittel på e-post-/slack-meldinger som sendes fra insert-metadata-*

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#123]
For eksempel når en bok stopper ved "Sett inn metadata for lydbok" så blir ikke det varslet om på e-post, siden det ville blitt ganske mye e-post. Men det kunne vært greit med en måte å se at den har blitt stoppet på hvis man lurer på hvorfor den ikke blir produsert som lyd. Så om det kunne stått en linje om det på Slack så hadde det vært nyttig. F.eks. "`555555 (Tittel) skal ikke produseres som lydbok`".

**Comment by josteinaj** [comment]
Har nå aktivert e-post også for bøker som ikke skal produseres. Men tror kanskje tittelen i e-posten (`self.title` er det vel) bør være noe sånt som "Sett inn metadata for {format}: {identifier} {skal | skal ikke} produseres ({tittel}) :+1::smile:". Nå står det bare "Sett inn metadata for {format}: lyktes :+1::smile:". Hvis steget feiler så kan det fortsatt stå "Sett inn metadata for {format}: feilet :-1::cry:".

**Comment by espso** [comment]
Dette er implementert, lukker denne
