### ISSUE TITLE
Ny innkommende linje for NLBPUB

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#124]
Revisjon av denne linja må holdes synkronisert med NLBs instruksjoner for oppmerking.

![plan for mottak av nlbpub - 2018-08-23](https://user-images.githubusercontent.com/295481/44522147-ebda5780-a6d5-11e8-9d33-cf77fdd0764a.png)

## `innkommende/NLBPUB`

Dette er en ny mappe, og er stedet hvor NLBPUB vi mottar fra eksterne produsenter skal legges.

## Mottakskontroll NLBPUB

Dette er et steg delt inn i to:
1. "krever ikke manuell gjennomgang", "helt valid", "valid/invalid", "grønn/rød", eller hva vi vil kalle det
2. "krever manuell gjennomgang", "advarsel", "gul", eller hva vi vil kalle det

Begge steg gjør de samme valideringene, og bør derfor muligens implementeres som én klasse i Python,
med to underklasser som arver fra denne klassen. På samme måte som det er gjort for "Sett inn metadata"-stegene.

Manuell gjennomgang trengs hvis:
- enten en Schematron feiler (Per lager første utkast)
- eller boken har tilhørende oppmerkingsinstruksjoner i QuickBase

### Begge steg:
- overvåker `innkommende/NLBPUB`
- gjør en validering for å avgjøre om boken er valid, og om den trenger en manuell gjennomgang
- hvis boken er invalid så skal steget feile

### Det første steget ("krever ikke manuell gjennomgang"):
- sender e-post
- utmappe: `grunnlagsfil/NLBPUB`
- boken går til utmappa hvis boken er valid, ikke trenger manuell gjennomgang, og ikke finnes i ut-mappa
- når boken går til utmappa så slettes boken fra inn-mappa
- hvis boken allerede finnes i ut-mappa så skal det ikke gjøres en validering, men:
    - det skal gå en e-post som sier at "Boken finnes i ut-mappa"
    - boken skal slettes fra inn-mappa

### Det andre steget ("krever manuell gjennomgang"):
- sender ikke e-post
- utmappe: `mottakskontroll/NLBPUB`
- boken går til utmappa hvis boken er valid og trenger manuell gjennomgang
- boken skal ikke slettes fra inn-mappa når boken kopieres til ut-mappa
- når en bok slettes fra inn-mappa, så skal den slettes fra ut-mappa

## `mottakskontroll/NLBPUB`

Denne mappen inneholder bøker som trenger en manuell gjennomgang.

## Manuell kontroll

Etter at bøkene i `mottakskontroll/NLBPUB` er manuelt kontrollert,
eventuelt med manuelle endringer, så skal boka kopieres manuelt til `grunnlagsfil/NLBPUB`.

## `grunnlagsfil/NLBPUB`

Dette er en mappe som inneholder boka sånn den er når vi godtar mottaket,
og fungerer som en backup-mappe.

## Mottatt NLBPUB

Dette er et enkelt steg som overvåker `grunnlagsfil/NLBPUB`, og kopierer
nye/endrede bøker til den nye `master/NLBPUB`-mappen. Dette steget trenger ikke sende
e-post med mindre det feiler (som ikke skal skje).

## Nordisk EPUB til NLBPUB

Dette steget bør bruke den nye `master/NLBPUB`-mappen som ut-mappe når vi har satt opp resten
av systemet.

## `master/NLBPUB` og `master/NLBPUB-valid`

Den nåværende `master/NLBPUB` skifter navn til `master/NLBPUB-valid` (sånn at vi slipper
å trigge alle bøkene vi har på nytt).

Den nye mappen `master/NLBPUB` vil fungere som en mappe der man kan gjøre manuelle endringer
i bøkene etter behov.

**Disse mappenavnene bør være det siste vi endrer. Innkommende linje for NLBPUB bør
være testet en del før vi kobler den på resten av systemet.**

## Valider NLBPUB

Flyttet til #136.

~~Dette steget skal overvåke `master/NLBPUB`, og legge bøkene i `master/NLBPUB-valid` dersom
de er valide. Bøker skal ikke stoppe her selv om de i følge valideringen trenger
manuell gjennomgang.~~

~~HTML-versjonen av dagens validator gjør dette:~~
- ~~valider HTML i henhold til [nordic-html5.rng](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/schema/nordic-html5.rng)~~
- ~~valider HTML i henhold til [nordic2015-1.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/schema/nordic2015-1.sch)~~
- ~~sjekk JPEG magic numbers: [px:nordic-check-image-file-signatures](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xproc/step/check-image-file-signatures.xpl) (dette kan vi kanskje droppe i NLBPUB)~~

~~Skjemafiler vi jobber med for NLBPUB ligger her: https://github.com/nlbdev/nlbpub~~

~~Så det vi vil validere gjøre i første omgang nå er:~~
- ~~valider HTML i henhold til [nordic-html5.rng](https://github.com/nlbdev/nlbpub/blob/master/schema/nordic-html5.rng) (NLBPUB-versjon)~~
- ~~valider HTML i henhold til [nordic2015-1.sch](https://github.com/nlbdev/nlbpub/blob/master/schema/nordic2015-1.sch) (NLBPUB-versjon)~~
- ~~valider OPF i henhold til [nordic2015-1.opf.sch](https://github.com/nlbdev/nlbpub/blob/master/schema/nordic2015-1.opf.sch) (NLBPUB-versjon)~~
- ~~valider nav.xhtml i henhold til [nordic2015-1.nav-references.sch](https://github.com/nlbdev/nlbpub/blob/master/schema/nordic2015-1.nav-references.sch) (NLBPUB-versjon)~~
- ~~valider HTML i henhold til Schematron fra Per for å avgjøre om boken trenger manuell gjennomgang~~

## Fremdriftsplan

- [x] ~~@espso implementerer første utkast til stegene~~
- [x] ~~@josteinaj ser gjennom og setter i drift for testing (med separate test-mapper)~~
- [ ] ~~@olavindergaard og @PerSennels tester oppsettet og kommer med tilbakemeldinger~~
- [ ] ~~@olavindergaard, @PerSennels og @josteinaj ferdigstiller første versjon av NLBPUB-skjemareglene (#137)~~
- [ ] ~~@josteinaj og @espso endrer fra test-mapper til mapper i drift~~

**Comment by josteinaj** [comment]
Jepp, det ser bra ut!

**Comment by josteinaj** [comment]
I fremtiden kan vi vurdere å kjøre en XSLT på boka mellom `master/NLBPUB` og `master/NLBPUB-valid`. I følge @tagerobert så vil de på Statped flytte litt rundt på innhold i boka, noe som krever at innholdsfortegnelsen oppdateres. Dette er noe som kanskje kunne blitt gjort automatisk her.

@espso: ikke tenk på dette i første omgang. Jeg bare skriver det her så vi kanskje husker det.

**Comment by josteinaj** [comment]
Den nye linja bør passere system-testen også. Fra før av så legger vi en bok i `innkommende/nordisk` for å teste alt annet, men nå har vi en annen løype inn. Det passer ikke helt 100% med sånn vi har testet hittil så vi får tenke litt på det, men en test må vi få til.

**Comment by espso** [comment]
Ja det er sant. Det riktige vil kanskje være å kjøre gjennom to runder, en med en nordisk epub og en med NLBPUB (altså kopiere en epub til hver mappe), der begge skal gå gjennom systemet for at det er godkjent.

**Comment by josteinaj** [comment]
Ja sant, det bør funke.

**Comment by josteinaj** [comment]
Kanskje diagrammet bør forenkles her. Mulig vi ikke trenger `mottakskontroll/NLBPUB`-mappa og den separate "Manuell sjekk av NLBPUB"-boksen. Ting som trenger manuell kontroll kan bli liggende i `mottakskontroll/NLBPUB` til de er kontrollert og kopiert over manuelt.

Tilsvarende er gjort for "NLBPUB til PEF"-steget.

**Comment by espso** [comment]
Hva er status her, hva skal vi gjøre videre med denne linja?

**Comment by josteinaj** [comment]
Denne må vi få jobbet videre med, men siden Olav og Per slutter så har arbeidet med NLBPUB stoppet midlertidig opp. Kanskje er dette noe vi kan starte med igjen når vi er ferdig med ansettelser. Kanskje like greit å kommentere ut disse boksene fra systemet inntil videre så det ikke blir så mye rot? Men saken må vi holde åpen.

**Comment by josteinaj** [comment]
Avhenger av: https://github.com/nlbdev/nlbdev/issues/90

**Comment by josteinaj** [comment]
Sånn det ser ut nå så kommer nok ikke egne NLB-retningslinjer til å bli noe av med det første. Vi kommer nok heller til å lene oss på 2020-1-versjonen av de nordiske retningslinjene. Lukker denne saken.
