### ISSUE TITLE
Feil i bøker til innlesing

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#125]
Fra @espso (https://github.com/nlbdev/produksjonssystem/issues/111#issuecomment-413117787):

> Legger merke til at det er en del epub-til-innlesing som går på nytt hver dag. Eksempel 626626 Syria.
> I utgave/inn/lydbok ligger det to forskjellige som hører til denne, (560326 og 560333). Det samme gjelder flere, som 628969 Ungarn (563082 og 562669)
> Flere: 629054, 628770, 225490, 224809, 224825, 224872, 224650, 224592, 627720, 223973, 224294, 224090, 223960, 222948, 626156, 223028, 625987, 625982, 222867, 222871    
> 
> smb://128.39.251.205/tekstproduksjon/Arkiv/utgave-inn/lydbok/560326
> smb://128.39.251.205/tekstproduksjon/Arkiv/utgave-inn/lydbok/560333

**Comment by PerSennels** [comment]
Har endret slik at epub-til-innlesing bare varsler, men ikke stopper, i forbindelse med mangelfull metadata.

**Comment by josteinaj** [comment]
Supert. Så idet boka kommer til epub-til-innlesing så er forventningen at:

- `schema:isbn` er definert
- `dc:publisher.location.original` er definert
- `dc:language` er definert
- `dc:language.original` er definert dersom boken er oversatt
- `dc:title.original` er definert dersom boken er oversatt
- `dc:contributor.translator` er definert dersom boken er oversatt

Stemmer?

Og utover dette så bør vi kanskje kreve at Bibliofil har katalogisert de feltene du har i `metadata.forventet` også? Altså at disse må finnes:

- `dc:creator`
- `dc:date.issued.original`
- `dc:publisher.original`
- `schema:bookEdition.original`
- `dc:contributor.narrator`

Stemmer?

**Comment by PerSennels** [comment]
Ja, og tidligere ble prosessen avbrutt dersom metadata i første gruppe ikke var på plass, men nå kjører prosessen uansett.

**Comment by josteinaj** [comment]
Forøvrig, når det gjelder `dc:creator` så er det ikke noe krav når det katalogiseres til at det skal finnes en hovedforfatter. I epub-to-dtbook-audio gjør vi derfor følgende for å bestemme hvem som skal stå i `<docauthor>`:

- Bruk `dc:creator` dersom det finnes (kan være flere)
- Ellers, bruk `dc:contributor.editor` (redaktør) dersom det finnes (kan være flere)
- Ellers, bruk `dc:publisher.original` (originalforlag) dersom det finnes (i praksis alltid nøyaktig étt)
- Ellers, bruk `dc:publisher` (forlag, altså typisk NLB) dersom det finnes (i praksis alltid nøyaktig étt)

Er dette logikk som trengs i epub-til-innlesing også? Bør vi generere et sett med docauthors når metadata settes inn i bøkene? Vi kunne for eksempel laget et sett med `dc:creator.docauthor`?

**Comment by espso** [comment]
De bøkene jeg snakket om i første kommentar er bøker som blir produsert som epub-til-innlesing på nytt hver dag, og lyktes, det er jo unødvendig, men vet ikke helt hvorfor det skjer. 

@josteinaj I utgave/inn/lydbok ligger det to forskjellige som er samme bok, (eks. 560326 og 560333) en av de burde kanskje slettes?

**Comment by PerSennels** [comment]
@josteinaj Jeg tenker at dersom `dc:creator ` **ikke** er katalogisert, så er det basert på et bevisst valg om at den informasjonen ikke er nødvendig. (Og hvis det ikke er tilfelle, så bør katalogiseringspraksis strammes opp). 
Og da er det bedre, i epub-til-innlesing, å kunne håndtere at den ikke er definert. Tenker at med den sekvensen du har i det forrige innlegget ditt, så risikerer du at `dc:creator` får en verdi som er unøyaktig, forvirrende og misvisende.

**Comment by josteinaj** [comment]
Da gjør jeg ingenting mer med det.

Forøvrig: alle valideringsregler som trengtes for normarc var der allerede. Jeg har nå lagt til validering av OPF- og HTML-metadata også.
