### ISSUE TITLE
Pingviner i epost for Linux

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#134]
Legge til pingviner etter hver lenke i epost, der man i Linux kan kopiere bildet for å få link til smb://. Per i dag funker linkene bare i Windows og hvis man prøver å legge til en smb link blir den fjernet i webmail.

**Comment by josteinaj** [comment]
Det ser i utgangspunktet bra ut nå, men lenkene starter med `(href)`, så de virker ikke enda:

```html
<img src="data:image/png;base64,iVBOR…DF17fodMaIVYAAAAASUVORK5CYII="
     alt="(href)/media/archive/rapporter/logs/2018-10/555763/2018-10-03_21-52-27.708-nordic-dtbook-to-epub/log.txt">
```

**Comment by espso** [comment]
Ser ut som jeg glemte at yesterday ikke alltid er samme dato... Alle mailene har dato 2018-10-04 fordi yesterday ble satt utenfor while løkken. Derfor benyttes logfiler som har gammelt format og linkene feiler.
