### ISSUE TITLE
Forbedre dagsrapporter

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#139]
- Vurdere å lagre som yaml eller noe tilsvarende i stedet for .txt med koder for å forklare hva det er. Dette vil gjøre det enklere å hente ut info, men må kunne appende på en god måte.
- Forbedre slik at den sendes når den er klar hver dag, i stedet for bare mellom 7-9, som kanskje kan bli problematisk hvis serveren er helt opptatt. Lagre mail etterpå som html, så kan systemet sjekke om dagsrapport html finnes. 
- Gjøre det mer klart hva som produseres og hva som feiler

**Comment by espso** [comment]
Det burde også være mulig å ikke få dagsrapport. Vanlig mail vil fortsatt sendes for administratorer ved feil, litt usikker på hva vi vil med det.

**Comment by josteinaj** [comment]
Det mest interessante (i min mening) når man skummer gjennom dagsrapportene står nederst i e-posten: `Totalt ble N produsert og M feilet`. Kanskje dette kunne stått øverst eller høyt oppe sånn at man ikke trenger å bla nedover i e-posten? Eller til og med i emnefeltet hvis det er plass?

**Comment by espso** [comment]
Godt forslag, skal se på det, og endre litt på teksten.

**Comment by espso** [comment]
Lukker denne. Har fikset på en del, men ikke gjort om fra .txt filer enda. Forbedre feilmeldinger er egentlig en annen sak fordi det i noen tilfeller ikke er noen meldinger markert med ERROR vet ikke systemet hvorfor prosessen har stoppet opp.
