### ISSUE TITLE
Konfigtråden tror det er skjedd endringer i yaml filen uten at det er det

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#140]
For øvrig så er det ofte den ikke viser riktig fjernet, lagt til mottakerliste. Dermed er det kanskje like greit å ikke ha noe/fikse.

2. nov: Følgende mottakere ble fjernet i common: default_librarian :
Siste endring på fil: fr. 19. okt. 2018 kl. 11.53 +0200

Ingen stor greie, men helt klart en bug

**Comment by josteinaj** [comment]
Er dette fortsatt et problem? Kanskje hvis vi får til et grafisk grensesnitt, så kan vi avvikle YAML-filen på en eller annen måte… Gjøre konfigurering gjennom API f.eks.

**Comment by espso** [comment]
Så ut som det fungerte greit når jeg testet i høst. Enig i at brukergrensesnitt for dette er bedre, men er vel lavt på lsita. Viktigere å få opp brukergrensesnitt for sluttbrukere.
