### ISSUE TITLE
Eksterne ebøker blir ikke produsert

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#141]
Er markert som: Format: E-bok ekstern produksjon i quickbase, har e-boknummer, men er ikke katalogisert.

**Comment by josteinaj** [comment]
@espso Jeg har ikke hørt noen klager om dette i det siste. Er dette fortsatt et problem?

**Comment by espso** [comment]
Kan reåpne hvis det dukker opp igjen.
