### ISSUE TITLE
Vurdere implementasjon av pipeline1

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#142]
Dette er mer et spørsmål, men vil trenge det hvis vi vil validere daisy202 eller så vidt jeg forstår automatisere TTS. Har gjort en testimplementasjon i forhold til automatisert ressursgenerering på DOD ved endringer på share. Får validert på riktig måte og lagt ved rapport.

Evt. hvis pipeline2 kan forbedres så er det også en mulighet

**Comment by josteinaj** [comment]
Vi kan godt legge til Pipeline 1 i produksjonssystemet.

Validering av DAISY 2.02 er delvis mulig i Pipeline 2 (dog den burde vært
forbedret så Pipeline 1 er nok best her inntil videre).

TTS tror jeg vi helst vil gjøre i Pipeline 2 på EPUB-bøkene våre, og så
konvertere fra EPUB til DAISY i etterkant. Dagens TTS (Brage/Filibuster)
krever Pipeline 1 siden vi ikke har implementert støtte i Pipeline 2 for
det, men vi vurde starte å eksperimentere med TTS i Pipeline 2 snart
egentlig sånn at vi er klare når vi får ny TTS. I Pipeline 2 så kan vi
styre TTSen med CSS, som kan bli veldig bra.

Jostein

Den fre. 2. nov. 2018, 10:47 skrev espso <notifications@github.com:

**Comment by espso** [comment]
Fint!
Jeg og Ammar testet pipeline2 validatoren, men den fant hverken feil ved filnavn eller mp3 filer, det kan jo selvfølgelig forbedres.
