### ISSUE TITLE
Automatisk produksjon av nyhetsbrev i punkt

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#143]
Ny pipeline:
- navn: Nyhetsbrev
- inn-mappe: ingen
- ut-mappe: `utgave-klargjort/punktskrift`

Skal regelmessig sjekke om det finnes nyhetsbrev for foregående måned (evt. alle foregående måneder?). Hvis nyhetsbrev ikke finnes så skal det produseres med Pipeline 2-skriptet `nlb:catalog-month`.

Boknummer for nyhetsbrev: 120209mmåååå, f.eks. 120209112018.

Mulighet til å få ut nyhetsbrev i HTML ment for produksjon i punkt med PIP ble lagt til i https://github.com/nlbdev/pipeline/commit/03b6a7bcf9fa04f2612403bf87cfe9a9e64a56b6.

@KariRudjord har testet hvordan nyhetsbrevet blir seende ut nå, og har følgende ønsker til forbedringer. Disse må gjøres i Pipeline 2 (https://github.com/nlbdev/pipeline/tree/nlb/modules/nlb/catalog-month):

1. Om boka – er det mulig å utelate denne sida for nyhetsbrev? Muligens lage en egen nyhetsbrevmal der Om boka ikke er med?
2. Innholdsfortegnelse: er fin for punktskriftbøker og lydbøker, men på studiebøker lister den plutselig opp alle boktitlene i innholdsfortegnelsen. Det blir litt too much. Se punkt 4 for forslag til endring.
3. Nyhetssaker fra elektronisk nyhetsbrev skal IKKE være med i punktskrift-nyhetsbrevet
4. Hvis enkelt å gjøre: Jeg kan tenke meg at Skjønnlitteratur for voksne etc (`<h2>`-er) settes som `<h1>` slik at de får ny side og layout som hovedoverskrifter. Da blir det lettere å finne fram for fingeren som leser. Og at hver innførsel/bok, dvs. forfatter, som nå står på `<h3>` i stedet står som `<p>` med blank linje foran `<hr class="emptyline"/>`. Da fylles sidene ut bedre, og det blir mer oversiktlig
5. Standardteksten vil jeg gjerne ha byttet ut med denne:

> Her finner du boklister med nye bøker fra NLB den siste måneden, både punktskriftbøker og lydbøker. Bestill gjerne bøkene selv på våre nettsider. Du kan også ta kontakt på telefon eller e-post.
> 
> Dersom du ønsker e-post med nyhetssaker fra NLB, kan du abonnere på vårt elektroniske nyhetsbrev ved å legge igjen din e-postadresse nederst på forsiden på nettsidene og trykke på «Abonner».
> 
> Nettside: www.nlb.no
> E-post: utlaan@nlb.no
> Telefon: 22.06.88.10

**Comment by josteinaj** [comment]
@espso har du tid til å lage selve pipeline'en til denne? Så kan jeg få fikset endringene som Kari nevner i Pipeline 2?

**Comment by espso** [comment]
Ja den er grei

**Comment by KariRudjord** [comment]
@josteinaj eller @espso  Kristin forteller at det noen ganger har vært feil i boklistene i nyhetsbrevet. En gang kom noen testproduksjoner med under studiebøker. En annen gang var det ingen bøker i listen. Det første er en feil man neppe kan planlegge for, men kan jeg få en rapport til punkt@nlb.no som forteller at nyhetsbrevet er produsert og hvor mange titler som gikk ut den aktuelle måned?

**Comment by espso** [comment]
Hvordan skal systemet trigge produksjon av nyhetsbrev? Ny tråd som ser etter mapper fra forrige måned?

**Comment by josteinaj** [comment]
Ja det er vel greiest. Sjekke ved oppstart og deretter en gang i timen kanskje?

**Comment by espso** [comment]
@josteinaj Blir det noe av dette, eller skal vi droppe det?

**Comment by KariRudjord** [comment]
Dette er noe jeg har høyt på ønskelista, da jeg må gjøre det manuelt hver måned. Nyhetsbrevet i punktskrift trenger ikke nyhetssakene, kun boklister. Hadde vært en drøm om det gikk av seg selv!

**Comment by josteinaj** [comment]
Vi har en pipeline for det allerede som står og kjører, men den fungerer ikke helt som den skal tror jeg. Bør jobbes med.

**Comment by espso** [comment]
Jeg implementerte pipelinen for et år siden ca., men da mener jeg det stoppet på generasjonen i Pipeline (?)

**Comment by josteinaj** [comment]
Bør implementeres på nytt uten bruk av `nlb:catalog-month`-skriptet, men heller ved bruk av APIet vårt.

1. Ved hjelp av APIet vårt, lag en HTML-fil
2. Legg HTML-filen i `utgave-klargjort/punktskrift` med tolvsifret boknummer
3. Nyhetsbrevet blir da automatisk produsert på samme måte som alle andre bøker og havner som en PEF i `utgave-ut/PEF`
4.

**Comment by josteinaj** [comment]
@RuneRismo har implementert dette. Vi har det ikke i et API enda. Vi får se hva vi gjør med det, men det tar vi i en annen sak.
