### ISSUE TITLE
Validere ASCIIMath

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#144]
ASCIIMath i bøkene våre i dag ser ut som dette:

```html
<span class="asciimath">x^2 + y^2 = z^2</span>
```

Jeg tror det er en god del feil i disse uttrykkene, vi bør i det minste validere at syntaksen er riktig.

Kan inkluderes både i validering av nordisk epub samt nlbpub.

Se også #145.

**Comment by olavindergaard** [comment]
Det er vel også aktuelt å legge inn validering av MathML? 
[](http://www.w3.org/Math/RelaxNG/mathml3/mathml3.rng)

**Comment by josteinaj** [comment]
Jepp, helt klart. Validering av MathML tror jeg faktisk vi har i den nordisk validatoren.

**Comment by josteinaj** [comment]
Forslag fra Ammar: konvertere til MathML. Hvis feiler => invalid.

**Comment by josteinaj** [comment]
@GauteR hva tenker STEM-sjefen om denne?

**Comment by GauteR** [comment]
Det ser ut på å gå på validering av uttrykk, Ammar sitt forslag kan funke, men automatisk konvertering er vanskelig siden enkelte bøker benytter "norsk AsciiMath" som ikke følger standard regler for AsciiMath. Så må i så fall konverteres til generell AsciiMath før det konverteres til MathML - og da blir det kanskje mye ekstra-arbeid. 

Mulige løsninger:
- **Billigst**: si at gamle bøker har gammelt format, og har mye feil. Akseptere at sånn er det.
- **Bedre, men tidskrevende og kanskje kostbar**: Ammar sitt forslag, evt. konvertere til standard AsciiMath, konvertere til MathML. Men selv om syntaks er riktig, blir ikke nødvendigvis de matematiske formlene riktig, så det får vi ikke gjort uten matematisk menneskelig kunnskap, tror jeg.
- **Best, men kostbar**: sende bøkene til nyoppmerking i India hvor de følger nye oppmerkingsregler for matematikk.

**Comment by josteinaj** [comment]
Vi går for den billigste løsningen. Uttrykkene er markert opp med `class="asciimath"` i tilfelle vi vil gjøre noe med dem i fremtiden. :+1:
