### ISSUE TITLE
Mulighet å implementere en pipeline uten inn eller ut mappe 

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#146]
Avhengighet for #143 uten inn mappe. Per nå er det en en del assertions og andre ting som går galt med inn mappe "None".

**Comment by espso** [comment]
Evt. så kan kanskje ut og inn være samme mappe? Litt usikker på hvordan det vil fungere i praksis
![image](https://user-images.githubusercontent.com/36958078/48419671-d6b31900-e758-11e8-94dc-6b7004909c86.png)

**Comment by josteinaj** [comment]
Tror ikke samme mappe er lurt nei. Kan se på det når jeg får tid.
