### ISSUE TITLE
Avisproduksjon (Schibsted)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#149]
Sette opp avisproduksjon i produksjonssystemet vårt. Vi får diskutere mapper og bokser, men jeg vil tro avisene bør genereres som masterfiler og havne i `master/NLBPUB`.

- laste ned aviser automatisk med produksjonssystemet
  - i første omgang laste ned til f.eks. `ikt` automatisk med eksisterende server
- tilpasse XSLTer hvis behov (lage fra bunnen av, men hente kode fra Pers XSLT der vi kan)
- .NET-kode må enten kjøres i Linux under Mono, eller skrives om til XSLT / Python

**Comment by josteinaj** [comment]
- [ ] @usama49 sørger for at avisfeeder blir tilgjengelig i en delt mappe (f.eks. en undermappe av `ikt`)
- [ ] @espso (gjerne sammen med @GauteR) setter opp ny pipeline for avisproduksjon. Denne vil kanskje ligne litt på "Nyhetsbrev punkt"? 
  - Plukker opp filer fra den delte mappen med feeder
  - sender feedene gjennom en XSLT
  - validerer DTBook-resultatet med Pipeline 2
  - lagrer resultatet i utgave-klargjort/DTBook-til-talesyntese
- [ ] @josteinaj lager XSpec test og klargjør tom XSLT-fil.
- [ ] @usama49 (gjerne sammen med @GauteR) sørger for at XSLTen fungerer

Hva tror dere om dette? Også samarbeider vi selvfølgelig underveis etter behov også.

**Comment by espso** [comment]
Det ser greit ut. Hvordan sørger vi for at TTS blir produsert og overført til share og bibliofil (abklar)?

**Comment by josteinaj** [comment]
Hmm, ja det var det da. Jeg tenkte først at vi legger det i "utgave-klargjort/DTBook-til-talesyntese", men det er jo bøker som behandles manuelt.

@usama49 Hvor lett er det å sende DTBøker til Windows-TTS-serveren og får en DAISY 2.02-bok tilbake?

**Comment by josteinaj** [comment]
Okay, etter prat med Ammar tidligere i dag:

- ny delt mappe på TTS-server er opprettet (jeg skal legge til denne på produksjonsserveren også), la oss kalle den "schibsted" inntil videre (ettersom dette blir en spesifikk linje for Schibsted-aviser)
- "schibsted/avisfeeder" - dette er inn-mappa. Filene her følger ikke normal boknummer-struktur, så konvertering skal ikke starte når disse filene endres/opprettes/slettes.
- "schibsted/dtbookfiler" - dette er ut-mappa. Den skal inneholder to undermapper ("parentdirs"): "archive" og "latest"
  - "schibsted/dtbookfiler/archive" - dette er mappa hvor vi legger avisene med normal 12-sifret boknummerering.
  - "schibsted/dtbookfiler/latest" - dette er mappa hvor vi legger nyeste versjon av avisene, med filnavn som dagens TTS-server forventer, altså "aftenposten.xml", osv.

**Comment by josteinaj** [comment]
## I Python:

1. sjekk regelmessig om ut-filer for i dag mangler (tilsvarende nyhetsbrev i punkt)
2. avbryt hvis ikke `schibsted/avisfeeder/[dagens-dato]` finnes
3. Grupper XML-filer fra `schibsted/avisfeeder/[dagens-dato]` basert på filnavn på "Aftenposten", "Bergens_Tidende", "Faedrelandsvennen" og "Stavanger_Aftenblad"
4. Send liste over filnavn for hver avis til en XSLT, som skal slå sammen alle filene til én XML-fil
5. Send hver av de fire sammenslåtte XML-filene til en XSLT som konverterer til DTBook
6. Lagre resultatet både som `schibsted/dtbookfiler/archive/[boknummer].xml` og `schibsted/dtbookfiler/latest/[avisnavn].xml`

## I XSLT (+ tester):

### `join-articles.xsl`
- main template: "main"
- output: midlertidig fil
- parameter `base-uri`: full sti til mappe med filer
- parameter `files`: kommaseparert liste med filnavn

### `schibsted-to-dtbook.xsl`
- input: midlertidig fil
- output: avis som DTBook

**Comment by josteinaj** [comment]
Det ser ut som det ligger noen få bilder i selve XMLen faktisk...

**Comment by espso** [comment]
Et problem er at systemet prøver å bruke boknummeret som er datoen 2019-03-19

**Comment by josteinaj** [comment]
Dette har vi hatt i drift en stund nå.
