### ISSUE TITLE
Automatisk synkronisering av lyd i Docker

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#152]
Ammars skript for synkronisering kan vi kjøre som et eget prosjekt i Docker, med grensesnitt mot produksjonssystem-APIet (#294).

https://www.readbeyond.it/aeneas/

~Dette er et Python-bibliotek. Med mindre vi kjører dette som en separat prosess så bør vi ha multiprocessing på plass først ettersom det kan ta en del ressurser.~

**Comment by usama49** [comment]
Det er gammel sak, script er  er windows baser og ligger på git. Der er ikke optimal å flytte i doker. Derfor jeg lukker saken.

**Comment by josteinaj** [comment]
Åpner denne igjen. Det er lav prioritet, men helst bør vi flytte alt over i Docker.

**Comment by josteinaj** [comment]
Lage web-API, kunne sende inn en bok og få en synkronisert bok ut.

**Comment by josteinaj** [comment]
Sende path til server i stedet for selve boka.

**Comment by josteinaj** [comment]
- lage kort beskrivelse / spesifikasjon
- oppgradere til nyere .NET
- dele opp i separate verktøy (forskjellige git repoer)
- prate med Eivind om hvordan dette påvirker rutiner

**Comment by josteinaj** [comment]
@usama49 er det noe du venter på i denne saken? Kan du og eivind lage en kort beskrivelse av dette? Hvis dere har et møte om det, så gjerne inkluder meg hvis dere vil.
