### ISSUE TITLE
temp-skript i produksjonssystemet

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#157]
Har en duplikat her, men vi lar begge være inntil videre siden vi har planlagt duplikaten allerede:
- https://github.com/nlbdev/nlbdev/issues/132

**Comment by josteinaj** [comment]
Se også oppfølgingssak: https://github.com/nlbdev/produksjonssystem/issues/330

**Comment by josteinaj** [comment]
@espso kan vi si at denne er ferdig? eller gjenstår det noe?

**Comment by espso** [comment]
Trenger litt mer tid for testing og å sette i prod.
