### ISSUE TITLE
DOD ressursgenerering

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#158]
Ny pipeline: resourcegenerator

Bruker api-kall til DOD (disse må være tilgjengelige fra produksjonssystemet) for å finne ut hvilke bøker som ligger i archive, og for å trigge generering av bøker som ikke finnes. 

#142 Hvis validator skal være med i samme pipeline. #157 hvis denne vil vi trolig ikke trenge det.

Hvis godkjent send mail til bibliotekar for eksemplarpåføring, hvis ikke til etterarbeid.

**Comment by espso** [comment]
Api kall er laget, men må deployes på DOD før det kan tas i bruk. Spørsmålet er om vi kan overvåke dodmappa med bøker @josteinaj? Altså ingen skriving bare overvåkning.

Det andre punktet er om pipeline1 er greit å ha med for å få med en validasjonsrapport.

**Comment by josteinaj** [comment]
Vi kan overvåke DOD-mappa hvis den er en delt mappe, og hvis vi monterer den på produksjonssystemserveren. Er det en delt mappe?

Jepp, det ville vært fint å støtte Pipeline 1.

**Comment by espso** [comment]
Montere dod blir nok helt rart. Filene må likevel uansett være der for å kunne generere ressurser. Kan legge til et fiktivt utlån slik at filene blir kopiert over og så vente en liten stund. Prøve noen ganger før det kommer en feilmelding. Da må vi i så fall se bort fra disse utlånene i statistikker og levere tilbake bøkene. Det burde finnes en bedre måte å gjøre det på...

Kan vi i så fall kopiere over pipeline1 så sette PIPELINE1_HOME i set-env og så peke på det skriptet i pipeline mappa som brukes? (Daisy202DTBValidator.taskScript)

**Comment by josteinaj** [comment]
Tror ikke jeg helt skjønner dette.

- Trenger vi å validere bøkene på DOD-serveren?
- Kan vi overvåke share istedenfor eller er det viktig at det kun er bøker på DOD-serveren som er listet opp i archive?
- Vil det hjelpe om DOD-tjenesten returnerer en liste over alle bøker på DOD-serveren gjennom et API-kall?

**Comment by espso** [comment]
Problemet som kan oppstå i dag er at filene blir oppdatert på share, men på DOD/dds er det fortsatt de gamle filene. Slik det fungerer i dag er at når et lån er gjort og boka ikke finnes på DOD flytter dds boka over til DOD og vannmerker. Det andre problemet er jo at boka må være utlånbar for å flyttes over, og vi vil helst ikke gjøre en bok utlånbar før vi har sjekket at den er ok og har generert ressurser.

Hvis det er sikret at de samme filene som ligger på DOD og share så kan vi validere bøkene på share i stedet. (DOD bruker filene på DOD for å generere ressurser og distribuere filer). Ammar vil helst validere bøkene for å trippelsjekke at alle filer er valide. Da vil også bøkene bli validert på et linux system slik at det oppdager casesensitive feil.

Å liste alle bøkene kan være en god plan for å få bedre oversikt.
