### ISSUE TITLE
Mottakskontroll NLBPUB: avsnitt som bør være tabelltekst

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#162]
Oppdaget av @PerSennels.

Eksempel:
```html
<p><em>Tabell 3.1. Forfektete verdier slik de fremkommer i verdigrunnlaget til tre store norske konsern i 2011.</em></p>
<table id="table_2">…</table>
```

Her bør avsnittet rett før egentlig være et `<caption>`-element.

Forslag:
- Advarsel når avsnitt rett før eller rett etter en tabell er utelukkende uthevet tekst (`<em>`, `<i>`, `<strong>` eller `<b>`).

**Comment by PerSennels** [comment]
Kan i tillegg sjekke om avsnittet før tabellen matcher følgende RegEx "`^(\d|\p{Lu}).+$`"
