### ISSUE TITLE
Erstatte original-isbn.csv med APIet

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#165]
Sannsynligvis noe som har sluttet å virke på den gamle styringsdata-serveren. Enten:

- fikse oppsettet på gammel styringsdata-server (enklest, men helst ikke, vi må få faset ut den serveren)
- lag lista fra en docker-container (bibliofil-interface, datavarehus eller book-interface, ingen av de er egentlig naturlige å bruke)
- flytt produksjonssystemet til en docker-container, og spør datavarehuset direkte med SQL (beste løsning, vil ta tid)

**Comment by matskober** [comment]
Hei Jostein!
Godt nytt år!

Kan du slette meg fra denne epostlisten?

Mats

**Comment by espso** [comment]
Kan vi kopiere over en original-isbn.csv til fellesdokumenter for å se om det fikser feilen med autotrigging?

**Comment by josteinaj** [comment]
Ja det er sikkert lurt. Jeg kan fikse.

Set ut som det er noe rettighetsproblemer som gjør at ikke den gamle styringsdata-serveren klarer å skrive fila.

**Comment by espso** [comment]
Ok da får vi se om det skjer noe med autotrigging..

**Comment by josteinaj** [comment]
Hmm, jo egentlig. Vi har ikke noe som erstatter det helt enda, men så lenge vi beholder den original-isbn.csv-fila som ligger der allerede inntil videre, så er det vel nok.

**Comment by josteinaj** [comment]
Denne blir ikke automatisk oppdatert lenger, men vi trenger å gjøre et oppslag på original-ISBN på en eller annen måte.

**Comment by josteinaj** [comment]
La oss bruke APIet her i stedet for.

1. Sjekk `/editions/<identifier>` for å finne identifikator for åndsverket
2. Sjekk `/creative-works/<identifier>?editions-metadata=simple` for å finne alle andre boknummer og deres formater

**Comment by josteinaj** [comment]
Gjort.
