### ISSUE TITLE
Autotrigging sett inn metadata

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#166]
Problemet er hvis bøker stopper i master/NLBPUB fordi her er det ingen autotrigging. Enten fordi metadata er feil eller ikke markert for produksjon i et format. Bøker kan bli liggende i lang tid når de burde vært produsert i et utformat.

Kan ikke skru på vanlig autotrigging fordi da vil tusenvis av bøker bli trigget hele tida som ikke er meningen at skal produseres i et format. En mulighet kan være å lage en annen trigging som kun tar de bøker som har feilet tidligere eller noe sånt.

Kanskje det går an å ha et steg for "Produseres i format" før sett inn metadata. Eller kanskje validering av metadata burde vært mye tidligere i systemet?

**Comment by josteinaj** [comment]
Lurer på om dette kanskje er jobben til "Oppdater metadata"-pipelinen. Den skal sørge for at metadata i bøkene er oppdatert. Men den forholder seg ikke til utgaver tror jeg, kun til selve åndsverket. Kanskje "Oppdater metadata" bør trigge "Sett inn metadata for …"-pipelinene på en eller annen måte. Eller kanskje rett og slett tråden som kjøres i "Oppdater metadata" bør flyttes inn i "Sett inn metadata"...

**Comment by espso** [comment]
Ja sant tenkte ikke på det at den allerede gjør det.

**Comment by espso** [comment]
#168
