### ISSUE TITLE
Autotrigge bøker i "insert-metadata"-stegene dersom de ligger i noen sin liste i Quickbase

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#168]
records.xml, som du får når du kjører /opt/quickbase/get-latest.sh, inneholder forskjellige queries som jeg tror er det som brukes av produsenter i Quickbase for å se hva de skal gjøre. For eksempel for punktskrift:

```xml
        <query id="25">
          <qyname>EPUB til punktskrift</qyname>
          <qytype>table</qytype>
          <qydesc>Denne rapporten inneholder en oversikt over EPUB-filer som er klare for produksjon i punkt.</qydesc>
          <qycrit>({&#039;17&#039;.EX.&#039;1&#039;}AND{&#039;178&#039;.XEX.&#039;1&#039;}AND{&#039;30&#039;.EX.&#039;1&#039;}AND{&#039;43&#039;.XEX.&#039;1&#039;})</qycrit>
          <qyclst>8.9.13.28.432.43.87</qyclst>
          <qyopts>nos.qws.</qyopts>
                  <qycalst>0.0</qycalst>
        </query>
```

Selve spørringen er vel her `({'17'.EX.'1'}AND{'178'.XEX.'1'}AND{'30'.EX.'1'}AND{'43'.XEX.'1'})`.

Hva feltene 17, 178 osv. er for noe står også i records.xml inni `<fields>`, for eksempel:

```
<field id="17" field_type="checkbox" base_type="bool">
          <label>Production approved</label>
          <nowrap>0</nowrap>
          <bold>0</bold>
          <required>0</required>
          <appears_by_default>0</appears_by_default>
          <find_enabled>1</find_enabled>
          <allow_new_choices>0</allow_new_choices>
          <sort_as_given>0</sort_as_given>
          <carrychoices>1</carrychoices>
          <foreignkey>0</foreignkey>
          <unique>0</unique>
          <doesdatacopy>1</doesdatacopy>
          <fieldhelp>This field is checked by the ordering agency when a production is approved. Productions can be invoiced once this field is checked.</fieldhelp>
          <audited>0</audited>
          <display_graphic>1</display_graphic>
          <does_total>0</does_total>
        </field>
```

`{'17'.EX.'1'}` betyr altså i dette tilfellet at avkryssingsboksen "Production approved" er huket av.

Mapping av disse feltene til metadata er definert her:

https://github.com/nlbdev/produksjonssystem/blob/master/xslt/core-utils-metadata/bookguru/quickbase-record-to-rdf.xsl

**Spørringen "EPUB til e-bok":**

`(({'14'.EX.'1'}AND{'17'.EX.'1'}AND{'37'.EX.'1'}AND{'44'.XEX.'1'})OR({'346'.EX.'1'}AND{'14'.EX.'1'}AND{'17'.EX.'1'}AND{'351'.XEX.'1'}))`

**Spørringen "EPUB til punktskrift":**

`({'17'.EX.'1'}AND{'178'.XEX.'1'}AND{'30'.EX.'1'}AND{'43'.XEX.'1'})`

**Spørringen "EPUB til e-bok" som pseudokode:**

```
  nlbprod:epubCatalogued is true
  AND nlbprod:productionApproved is true
  AND nlbprod:formatEbook is true
  AND nlbprod:ebookProductionComplete is false
OR
  nlbprod:formatEbookExternalProduction is true
  AND nlbprod:epubCatalogued is true
  AND nlbprod:productionApproved is true
  AND nlbprod:externalProductionProductionComplete is false
```

**Spørringen "EPUB til punktskrift" som pseudokode:**

```
  nlbprod:productionApproved is true
  AND nlbprod:formatBrailleClub is false
  AND nlbprod:formatBraille is true
  AND nlbprod:brailleProductionComplete is false
```

`nlbprod:epubCatalogued` og `nlbprod:productionApproved` trenger vi egentlig ikke å sjekke, for om ikke de er huket av så kommer de ikke ned til `master/NLBPUB` uansett.

Istedenfor å sjekke "`nlbprod:formatEbook is true`" så kan man i produksjonssystemet sjekke should_produce for "XHTML",
og tilsvarende istedenfor å sjekke "`nlbprod:formatBraille is true`" så kan man sjekke `should_produce` for "Braille".

Og disse `nlbprod:ebookProductionComplete` og `nlbprod:externalProductionProductionComplete`, kanskje vi kunne
skilt de ut i en egen funksjon kalt f.eks. `production_complete`, som fungerer på tilsvarende måte som `should_produce`? `production_complete` må isåfall returnere `True` dersom boken ikke finnes i Quickbase, ellers tror systemet at ingen gamle bøker er ferdige.

Isåfall kan vi i insert-metadata sjekke `if should_produce and not production_complete` tror jeg...

@espso hva tror du?

**Comment by espso** [comment]
Skjønte ikke helt hva som var greia med syntaxen til de spørringene, men ellers tror jeg det vil fungere bra. 

Should_produce vil da altså returnere true for alle bøker som er huket av i det formatet? 
Skal production_complete også ligge i insert_metadata?

**Comment by josteinaj** [comment]
Dersom boka ikke finnes i Quickbase men er katalogisert i Bibliofil, eller finnes i Quickbase og er huket av for det relevante formatet, så returnerer `should_produce` True.

`should_produce` tror jeg ligger i `Metadata`? `production_complete` bør ligge samme sted.

**Comment by espso** [comment]
Vi burde kanskje vente med denne til det ikke er så mye kø / insert-metadata går så tregt?

**Comment by josteinaj** [comment]
Nei jeg tror det er lurt alikevel. Ikke alltid greit for folk å vite om en bok er trigget eller ikke. Hvis det trigger for mange bøker så kan vi slå det av igjen. I utgangspunktet skal det vel ikke trigge så mange bøker?

**Comment by espso** [comment]
Nei så lenge det ikke er veldig mange som ligger og venter i Quickbase skal det vel gå bra.

**Comment by josteinaj** [comment]
Skal være fikset nå, fra og med ad9ec70e176ff2b800bd34dd249397deaf87888d. Logikken er ikke 100% lik den som er i Quickbase.

Punktskrift anses som ferdig produsert hvis en av disse er huket av:
- Punktskrift ferdig produsert
- Punktklubb ferdig produsert
- Taktilt trykk ferdig produsert

DAISY 2.02 anses som ferdig produsert hvis en av disse er huket av:
- DAISY 2.02 ferdig produsert
- DAISY 2.02 TTS ferdig produsert

XHTML anses som ferdig produsert hvis en av disse er huket av:
- E-bok ferdig produsert
- Ekstern produksjon ferdig produsert

For `insert-metadata-*`-stegene og `epub-to-dtbook-audio`-steget så blir ting kun automatisk trigget dersom boka skal produseres, og ikke er ferdig produsert. Boka må også finnes i Quickbase for å bli autotrigget.

**Comment by josteinaj** [comment]
Det ser ikke ut til at dette virker ordentlig. Gjenåpner.

**Comment by josteinaj** [comment]
Skal nå være implementert ved at alt som ligger i Bibliofil i riktig format men uten eksemplarer antas å være til produksjon og dermed trigges.
