### ISSUE TITLE
Feilmelding når boken slettes

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#173]
```
Endret bok i mappa: 553099

Epub does not exist anymore./media/archive/master/NLBPUB/553099

An error occured while handling the book

Traceback (most recent call last):
  File "/opt/produksjonssystem/produksjonssystem/core/pipeline.py", line 916, in _handle_book_events_thread
    result = self.on_book_modified()
  File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 28, in on_book_modified
    return self.on_book()
  File "/opt/produksjonssystem/produksjonssystem/insert_metadata.py", line 36, in on_book
    epub = Epub(self, self.book["source"])
TypeError: __init__() should return None, not 'bool'
```

Her bør det vel ikke vises stacktrace i det hele tatt. Mangler antageligvis en try/except i insert_metadata.

**Comment by espso** [comment]
Starta på denne tidligere så kan sikkert fortsette..

**Comment by espso** [comment]
Greit @josteinaj? Tror dette skal fikse problemet
```
try:
            epub = Epub(self, self.book["source"])
        except Exception:
            self.utils.report.error("Klarte ikke å initialisere epub {}. Avbryter..".format(self.book["name"]))
            return False
```

**Comment by josteinaj** [comment]
Usikker på om det er en løsning eller om det bare skjuler problemet. Er det sånn at det er `on_book_modified` som blir kalt mens det egentlig er `on_book_deleted` som burde blitt kalt? I så fall er det kanskje et problem med `get_main_event`-funksjonen.

**Comment by josteinaj** [comment]
`get_main_event` burde vi egentlig skrevet en unit test for.

**Comment by espso** [comment]
Jeg tror det skjer fordi det tar litt tid å slette filene, men er ikke helt sikker. Skjer ikke når jeg sletter filer lokalt. Altså tror jeg det er feil funksjon som blir kalt som du sier.

Tror uansett ikke den over fikser problemet umiddelbart, fordi epuben blir initialisert, men feil/tom. epub() kan returnere none så kan hver enkelt pipeline stoppe ved epub none i stedet for try/ except.

**Comment by josteinaj** [comment]
Dette er vel faktisk en duplikat av 100 issues tidligere: #73
