### ISSUE TITLE
Automatisk trigging når metadata endres

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#183]
Ny versjon av "Oppdater metadata".

- overvåk `metadata`-mappen for endringer
  - bry seg kun om toppnivå-filer (altså ignorer quickbase- og bibliofil-spesifikke filer)
  - bry seg kun om OPF- og HTML-metadata (RDF-metadata kan endre seg oftere og inneholder mye irrelevant informasjon
  - ignorer endringsdato - bør kun sjekke MD5 av OPF/HTML

Trenger ikke å bruke en tråd som itererer over alle bøker og oppdaterer dem lenger. Metadata vil oppdateres i separat docker-container. Så dette blir litt mer som en normal pipeline.

**Comment by espso** [comment]
Burde kanskje også gjøres for DTbook til TTS? Bruker den metadata mappen?

**Comment by josteinaj** [comment]
Ja, sant det. Godt poeng. Vi lager to instanser av denne da.

**Comment by josteinaj** [comment]
Kan eventuelt gjøres ved å bruke APIet, og mellomlagre md5-verdiene. Hvis en md5-verdi endrer seg, så kan vi trigge boka.
