### ISSUE TITLE
Sjekk om katalogposter er slettet eller ikke

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#188]
Vi får ikke ut informasjon om en katalogpost er slettet eller ikke via SRU. Antageligvis er det best å basere dette på databasedumpen fra Bibliofil, men den er ikke helt klar enda.

Hvis vi finner en enkel midlertidig workaround for dette så hadde det vært bra.

**Comment by espso** [comment]
Aner ikke hvordan dette skal gjøres hvis det ikke finnes i SRU

http://websok.nlb.no/cgi-bin/rest_service/nlb_metadata/1.0/412020

Vet ikke om man kan bruke denne

**Comment by josteinaj** [comment]
Ja der ja, den bør vel funke som en midlertidig løsning.

**Comment by josteinaj** [comment]
ef63124ab06eddf172da270b9d2504ee7b0638f4

**Comment by josteinaj** [comment]
Dette virker tydeligvis ikke. 412020 kommer opp i valideringsrapporten for 563420 hele tiden.

**Comment by josteinaj** [comment]
Bibliofil har nå fikset sånn at SRU returnerer tag 000 også, sånn at vi kan sjekke den direkte.

**Comment by josteinaj** [comment]
1ba4aad8c7424496d0430ff8d0be3a18123b736a
