### ISSUE TITLE
Autotrigging NLBPUB til innlesingsklar Epub

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#190]
Ca. 1000 blir trigget for produksjon hele tida. Må undersøkes og fikses.

**Comment by espso** [comment]
Mulig det er relatert til #165. Finner hvertfall ikke flere formater i original-isbn for mange av de jeg har sjekket.

**Comment by josteinaj** [comment]
Tror ikke dette er et problem lenger?
