### ISSUE TITLE
Maler for egendefinerte eposter ved oppdateringer fra produksjonssystem

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#191]
Sette opp et mal-basert system for å kunne sende ut epost med "Full", "Avansert" eller "Standard" detaljnivå ved oppdateringer/feilmeldinger i produksjonssystemet. Pga. at ikke alle trenger fulle detaljer om hva som skjer i alle steg av prosessene.

**Comment by josteinaj** [comment]
Høres lurt ut med flere detaljnivåer. Kanskje dette bør gjøres innenfor web-grensesnittet istedenfor e-postene vi har i dag, jeg vet ikke helt. Vi bør uansett forbedre e-postene, jeg laget en egen sak på det her nå: #192

**Comment by josteinaj** [comment]
Lukker denne. Vi fokuserer heller på web-grensesnitt.
