### ISSUE TITLE
Ny utforming av e-post

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#192]
- forenkle (mindre tekst, kun det helt essensielle, det viktigste først)
- gjøre penere (farge, font, utforming, bruke NLBs profilmanual)

Kanskje vi kan finne noen fine maler fra nett og basere det på dem.

**Comment by GauteR** [comment]
Når vi skal utforme et webgrensesnitt kan vi lage til et bedre system for overvåking som ikke spammer like mye, eller evt. spammer om bruker velger det. Og da vet jeg ikke hvor aktuelt det er å utforme nye mailer.

**Comment by josteinaj** [comment]
Det er sant. Samtidig så vil det antageligvis være mye likt i e-posten og i web-grensesnittet. Så om man lager en fint web-grensesnitt så kanskje man kan gjenbruke mye i e-posten.

**Comment by josteinaj** [comment]
Lukker denne. Vi fokuserer heller på web-grensesnitt.
