### ISSUE TITLE
Gjøre det mulig å ikke hente metadata for en produksjon

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#195]
Vil alltid prøve å hente metadata i pipeline.py, blir et problem hvis en produksjon ikke har boknummer.

**Comment by josteinaj** [comment]
Jeg tror dette handler om å kunne sende testproduksjoner gjennom produksjonssystemet, men er ikke helt sikker. Tar det i så fall gjennom andre saker.
