### ISSUE TITLE
Håndtere "Bolig" og "Lørdag" i Aftenposten

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#198]
Disse kommer nå opp som tema-overskrifter (h2) blandet inn i resten av avisen. Men disse bør bli til egne deler etter Del 1 og Del 2.

Dette kan mappes i toppen av Schibsted-XSLTen.

**Comment by espso** [comment]
Har vi merket noe til endringene som ble gjort i aftenposten? Bare en del i stedet for flere?

**Comment by josteinaj** [comment]
Bolig og Lørdag er ikke merket opp som egne "deler" i XMLen, så vi trenger regler for dem. Men kultur/sport blir fortsatt lagt i Del 2, og A-magasiner (på fredager) kommer også som egen del.

**Comment by josteinaj** [comment]
@nlbdev/utviklere hvordan var status for avisene? De skulle vi slutte med for en stund fordi grunnlagsfilene skulle endre seg, var det sånn? Bare lurer på om vi kan lukke denne…

**Comment by josteinaj** [comment]
@usama49 var dette fikset i det nye avisskripet du lagde i 2020?
