### ISSUE TITLE
Schibsted-aviser: identifisere "kladder"

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#199]
Lørdag 6.april begynte avisen for eksempel med massevis av dette:

![Capture+_2019-04-06-11-06-27](https://user-images.githubusercontent.com/295481/55735887-864b9900-5a22-11e9-9fca-4c113a16e41e.png)

![Capture+_2019-04-06-11-08-03](https://user-images.githubusercontent.com/295481/55735889-877cc600-5a22-11e9-810e-c56a1be9461e.png)

**Comment by josteinaj** [comment]
@usama49 var dette fikset i det nye avisskripet du lagde?

**Comment by usama49** [comment]
Nye skript henter bare tekst . kan lukke saken
