### ISSUE TITLE
Fotnoter kan ikke stå i teksten etter daisy202-validator?

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#201]
epub til innlesing - Må sjekkes XSLT

**Comment by josteinaj** [comment]
Det kan også hende dette er en Hindenburg-sak, og ikke en sak for oss.

**Comment by espso** [comment]
Eivind som meldte inn saken, mente det kanskje måtte fikses i XSLT

**Comment by josteinaj** [comment]
Ja, vi kan antageligvis fikse det i XSLT. Får se noen eksempler. Men vi har vel ikke lyst til å gjøre tilpasninger som forringer EPUBen bare for å få en gyldig DAISY 2.02-bok ut. Tror jeg. Vi får se på et eksempel en gang.

**Comment by josteinaj** [comment]
Dette har vi løst nå, ved at vi rett og slett lar fotnotene stå der de er (ikke flytter de inn i teksten).

Oppfølgingssak: https://github.com/nlbdev/nlbdev/issues/8
