### ISSUE TITLE
Feil ved nedlasting: Vannmerkingsfil

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#202]
Filen blir slettet ved innlevering og ikke regenerert ved nytt lån som fører til feil i nedlasting.

Oppdaget på Gautes bruker (111694) bok nr 627662, samt Josteins bruker. Kan være grunn til at mange feiler på nedlasting.

**Comment by GauteR** [comment]
Ser ut som synk problem.

**Comment by josteinaj** [comment]
Flyttet til https://github.com/nlbdev/distribusjonssystem/issues/6
