### ISSUE TITLE
Fjerne sideskift fra talesyntese-bøker, kun for tidsskrift

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#203]
- fjern `<pagenum …>`-elementer i [xslt/epub-to-dtbook-audio/dtbook-cleanup.xsl](https://github.com/nlbdev/produksjonssystem/blob/master/xslt/epub-to-dtbook-audio/dtbook-cleanup.xsl)
- lag test for å sjekke at `<pagenum …>`-elementer blir fjernet i [xslt/epub-to-dtbook-audio/dtbook-cleanup.xspec](https://github.com/nlbdev/produksjonssystem/blob/master/xslt/epub-to-dtbook-audio/dtbook-cleanup.xspec)

**Comment by Yazazie** [comment]
NB: Skal bare fjerne sidenummer i tidsskrifter. Ikke andre DAISY-bøker.
