### ISSUE TITLE
Ascii kodet HTML tolkes ikke riktig for &#9658;

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#206]
Bok 852374

![Eksempel](https://user-images.githubusercontent.com/19590971/63511970-dcf1d500-c4e2-11e9-846a-cb85e13c5225.jpg)

**Comment by josteinaj** [comment]
Hvor er denne boken? Eventuelt har du kildekoden for den infoboksen?

**Comment by usama49** [comment]
boka skal kodes  `&#9658; `  og ikke   `&amp;#9658;`

**Comment by GauteR** [comment]
Varslet Statped om at de skal endre bøkene.
