### ISSUE TITLE
Ny pipeline NLBPUB til Epub

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#208]
Pipeline for Epub til distribusjon.

- Inn: utgave-klargjort/ebok
- Ut: Share?

Splitting av filer og evt. sette inn informasjon i starten av boka gjøres i XSLT. Hele poenget er at denne Epuben skal være klar til distribusjon. Vi må også ta stilling til om den skal pakkes som .epub eller bare mappe.

Vil være avhengig av at metadata er på plass før produksjon starter.

**Comment by josteinaj** [comment]
Denne finnes nå.

Videre arbeid:
https://github.com/nlbdev/produksjonssystem/issues/136
https://github.com/nlbdev/nlbdev/issues/3
