### ISSUE TITLE
Ny pipeline: Lagre tidligere versjoner av bøker fra master/NLBPUB

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#21]
Vi trenger et "arkiv"-steg med `master/NLBPUB` som inn-mappe, og `master/tidligere` som ut-mappe.

Når det kommer en ny eller endret bok i master/NLBPUB så skal det tas en sikkerhetskopi av boka under `master/tidligere/{boknummer}/{versjon}`
- `{boknummer}` er boknummeret på samme måte som for alle andre pipelines
- `{versjon}` bør bestå av en tidsangivelse og et løpenummer (teller fra 1 og oppover). Eventuelt bare tidsangivelse (det er kanskje best). For eksempel: "1.2018-06-01T09:52:14" eller bare "2018-06-01T09:52:14".
- filer som ikke er endret i forhold til forrige versjon av boka lagres som en tom fil (0 bytes) for å unngå dobbeltlagring
- filer som er slettet i forhold til forrige versjon av boka lagres ikke i det hele tatt

Er åpen for andre forslag også, men dette kan være en måte å gjøre det på.

**Comment by josteinaj** [comment]
@espso: jeg setter deg på denne. Ok?

**Comment by espso** [comment]
Ja den er grei

**Comment by espso** [comment]
@josteinaj Testet du denne? Evt. hva bør gjøres før den settes i drift

**Comment by josteinaj** [comment]
Ikke fått testet enda, skal prøve å få testet i dag eller i morgen.

**Comment by josteinaj** [comment]
Det fungerer bra. Jeg lurer bare litt på hva som bør lagres i hver nye versjon.

Om jeg forstår implementasjonen rett sånn den er nå:

- hvis det finnes en tidligere versjon som er identisk den nye versjonen; lagre den nye versjonen som en tom mappe
- ellers; lagre en full kopi av filsettet i en mappe

Hvis man lager versjon A, så endrer man noe sånn at man får versjon B, og så finner man ut at det burde man ikke gjort alikevel og går tilbake til versjon A, så vil den nyeste versjonen i backup-mappa i så fall fortsatt være versjon B. Stemmer ikke det?

Hva tror du om følgende:

- lagre kun filer som er nye eller modifisert sammenlignet med forrige versjon (ikke sammenlign med tidligere versjoner enn det)
- for å gjenskape en versjon er det da bare å starte med eldste versjon, og så kopiere nyere og nyere mapper over i den for å gå til den versjonen man ønsker
- for slettede filer kunne man laget en `.deleted-files`-fil i mappen til versjonen som lister opp alle filer som finnes i tidligere versjoner, men som ikke skal finnes i siste versjon

For eksempel:

```
2018-06-21T15:00:00/
  content.xhtml  # første versjon av boka
```

```
2018-06-21T16:00:00/
  content.xhtml.temp  # en kopi av content.xhtml lagt til ved et uhell
  image.png           # lagt til et bilde i boka
```

```
2018-06-21T17:00:00/
  .deleted-files  # inneholder "content.xhtml.temp" etter at den ble slettet
```

```
2018-06-21T18:00:00/
  .deleted-files  # inneholder fortsatt "content.xhtml.temp"
  package.opf     # ny fil lagt til boka i denne versjonen
```

Hvis man lager seg en mappe med innholdet av den eldste, og så kopierer inn innholdet fra nyere og nyere versjoner, så vil man ende opp med dette:

```
  content.xhtml.temp # denne er med ...
  .deleted-files     # ... men skal slettes står det her
  content.xhtml
  image.png
  package.opf
```

**Comment by espso** [comment]
Da tenkter vi litt mer på denne. Hvis man lagrer full kopi hver gang det er noe nytt blir det mye dobbeltlagring og vil bli et problem hvis vi legger til nye filer som lydfiler. Fordelen er at det er enkelt å gå til en versjon. Det beste vil kanskje være som du foreslår å lagre de nye filene som er endret, men da må vi ha en oversikt over hva som er endret tidligere. Det funker ikke å fun sjekke mot forrige versjon, for den kan være tom og da lagres hele på nytt.

En slik oversikt kan lages som en dictionary (Blir vel en slags changelog)

**Comment by josteinaj** [comment]
Ja, dicionary kan kanskje bygges opp som dette:

```python
# Gå gjennom alle versjons-mapper og finn nyeste av hver fil:
{
    "content.xhtml": "/tmp/archive/master/tidligere/555555/2018-06-21T15:00:00/content.xhtml"
    "content.xhtml.temp": "/tmp/archive/master/tidligere/555555/2018-06-21T16:00:00/content.xhtml.temp"
    "image.png": "/tmp/archive/master/tidligere/555555/2018-06-21T16:00:00/image.png"
    "package.opf": "/tmp/archive/master/tidligere/555555/2018-06-21T18:00:00/package.opf"
}
```

```python
# Fjern filer som er listet opp i `.deleted-files`:
{
    "content.xhtml": "/tmp/archive/master/tidligere/555555/2018-06-21T15:00:00/content.xhtml"
    "image.png": "/tmp/archive/master/tidligere/555555/2018-06-21T16:00:00/image.png"
    "package.opf": "/tmp/archive/master/tidligere/555555/2018-06-21T18:00:00/package.opf"
}
```

Deretter kan man sammenligne filene i dictionary med den nye versjonen av boka for å se om det er noen forskjeller.

**Comment by espso** [comment]
Har laget denne på nytt nå. Hvis det er noen endriger, lagre de filene som har endringer, ellers lag en tom mappe (Trenger vi en tom mappe?). Har også en oversikt over hva som er slettet. Sletter ingen av filene i de gamle mappene, for å alltid ha muligheten til å rulle tilbake.

Har ikke funnet noen enkel måte å gjenopprette en spesiell versjon på, kan muligens lage et skript som legges ved siden av. En mulighet er å lagre recent_files.yml i under hver versjonsmappe med en dictionary som peker på filene. Derfra vil det være enkelt med et skript å lagre de filene i en mappe. Det blir kanskje litt rotete å legge ved skript overalt. Hvis ikke kan man bruke metoden med å kopiere en og en mappe frem til den versjonen man vil ha.

**Comment by espso** [comment]
Oppdatert med ```{relpath: time_created/relpath}``` i files.yml slik at flere filer kan hete det samme i forskjellige mapper. Open with er brukt i stedet for open close etter kommentarer fra @josteinaj. Filer i previous mappen kan gjenopprettes ved å kopiere over produksjonssystem/tests/restore_files.py over til ønsket mappe (eksempel: /home/espso/Desktop/book-archive/master/NLBPUB-tidligere/55829418/2018-08-16T14:19:57) så kjøre kommando`i terminal: ```python3 restore_files.py```

**Comment by josteinaj** [comment]
Denne ser vel ut til å fungere fint?

@espso hvis du ikke planlegger noen endringer her så kan du godt lukke denne.
