### ISSUE TITLE
Usikker på om daisy-pipeline installasjonen fungerer?

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#218]
Funket kun hvis jeg kopierte over gammel installasjon. Gjorde det som stod i readme

**Comment by josteinaj** [comment]
Ok, ja mulig det er noe feil i README.

Håper å få det satt opp i Docker i stedet for: https://github.com/nlbdev/produksjonssystem/issues/219

**Comment by josteinaj** [comment]
Arkiverer denne til fordel for #219.
