### ISSUE TITLE
Kjør Pipeline 2 som Docker-container

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#219]
Avhenger av: https://github.com/nlbdev/pipeline/issues/230

**Comment by josteinaj** [comment]
Kanskje kjøre alt annet enn PIP i Docker inntil videre…?

**Comment by josteinaj** [comment]
PIP-versjonen som vi bruker i drift per i dag finnes nå som `nlbdev/pipeline:2018-working-pip`, så det finnes nå docker images for alt vi trenger i Pipeline 2.

**Comment by josteinaj** [comment]
Jeg tror dette vil kunne løse mye treghet i systemet.

Foreslår et pool i drift med f.eks.:

- 2 replicas av `nlbdev/pipeline:2018-working-pip`
- 4 replicas av `nlbdev/nordic-epub3-dtbook-migrator:2019-06-12`
- 1 instans av Pipeline 2 satt opp på selve produksjonssystemet (som nå) men kun brukt dersom ingen av de andre er tilgjengelig (dermed kan Statped fortsatt bruke denne løsningen hos seg til å begynne med)

Jeg har begynt på å lage et Pipeline 2 Web API-grensesnitt i `daisy-pipeline`-branchen: https://github.com/nlbdev/produksjonssystem/compare/daisy-pipeline. Trenger å få satt av tid til å gjøre den ferdig.

Nyhetsbrevet vårt produseres i dag på produksjonssystem-instansen av Pipeline 2. Vi må også sørge for at en instans av `nlbdev/pipeline:2018-working-pip` med tilhørende `daisyorg/pipeline-webui:v2.7.0` er tilgjengelig for bruk i manuell produksjon.

Hvis vi trenger skript fra den offisielle versjonen av Pipeline 2 så kan vi legge til replicas av `daisyorg/pipeline-assembly:v1.13.4` (eller nyere) i poolen.

Hvilke skript som kan brukes i hvilke instanser må defineres i produksjonssystemet (sånn at f.eks. nordisk epub-validering skjer i `nlbdev/nordic-epub3-dtbook-migrator:2019-06-12` og ikke i `nlbdev/pipeline:2018-working-pip`)

**Comment by espso** [comment]
@josteinaj har fikset
