### ISSUE TITLE
API for web-grensesnitt

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#224]
Hvis vi lager et bedre API mot produksjonssystemet så kan kanskje https://github.com/nlbdev/toolbox brukes som frontend? Se også https://github.com/nlbdev/produksjonssystem/issues/167

**Comment by espso** [comment]
Denne saken er veldig uklar. "Bedre api", hvis vi skal gjøre noe med det må vi se litt på hva vi vil trenge i frontend, og deretter utvikle det vi trenger i backend. Evt. så kan vi se på endpoints vi uansett vil trenge, men må likevel planlegges og spesifiseres.

**Comment by josteinaj** [comment]
Enig. Lukker denn saken.
