### ISSUE TITLE
Fikse bilder som er merket opp feil

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#234]
Webarch markerer opp bilder feil (i min mening):

```html
<section id="d6e938">
   <div epub:type="pagebreak" class="page-normal" id="d6e940-1" title="1"/>
   <figure class="image">
      <img src="images/ar-42105-tf-3102857-1-normal.jpg" alt="image" id="d6e942"/>
   </figure>
</section>
```

Her burde det ikke være et section-element, bildet er jo ikke et kapittel i seg selv. Dette medfører problemer når vi skal lage innholdsfortegnelsen (se f.eks. create-hidden-headlines.xsl).

Vi kan fikse dette i steget vi ikke har implementert enda, som vil komme mellom `master/NLBPUB` og `master/NLBPUB-valid`, hvor vi skal validere og fikse gammel oppmerking.

Når vi fjerner section-elementet så må vi passe på at det ikke er noen steder i boka som refererer til id'en til section-elementet. I så fall må disse referansene oppdateres, eller id'en bevares i f.eks. et tomt div-element.

Problemet er meldt til Thomas/Elise/Sobia, som kanskje tar det videre med Webarch for fremtidige bøker, men det er greit å legge inn en regel som også håndterer eksisterende bøker som har denne oppmerkingen.

**Comment by josteinaj** [comment]
@eliseaas er dette fortsatt et problem?

**Comment by eliseaas** [comment]
> @eliseaas er dette fortsatt et problem?

Sjekket et par titler produsert med Webarch og kan ikke se lik oppmerking der.

**Comment by josteinaj** [comment]
Ok. Da lukker jeg denne saken.
