### ISSUE TITLE
Valideringsregel for MathML

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#247]
> Hvis mathml mangler `altimg` send tilbake

Gjelder i hovedsak DTBook, men kan gjelde for alle produksjoner med MathML

**Comment by espso** [comment]
@josteinaj Skal dette inn i skjemaregler for validering eller gjør vi det som en slags annen validering som kan gjøres på en annen måte?

**Comment by espso** [comment]
```
EPUBCheck completed
2020-05-22 13:53:41,583 INFO     [book in prepare-for-ebook     ] ERROR(OPF-014): ..2i19us1t/229677.epub/EPUB/566477.xhtml(-1,-1): The property 'mathml' should be declared in the OPF file.
```

**Comment by josteinaj** [comment]
Krever vi alltid altimg? I så fall bør vi gjøre det til en del av NLBPUB-valideringen (som ikke er lagt til i prodsys enda), og kanskje også i mottakskontroll. Vi kan vel alltids generere altimg etter behov for gamle bøker.

"mathml" må være deklarert i OPFen for HTML-filer som inneholder MathML ja. I NLBPUB har vi bare én innholdsfil, men etter splitting i flere filer for e-bokdistribusjon så må vi sjekke en og en fil og legge på property etter behov. Sikkert kjekt med en egen funksjon i epub.py for dette.

**Comment by espso** [comment]
Dette burde nok inn i mottakskontroll, fordi målet er å sende tilbake hvis det ikke er markert opp etter de kravene vi setter.
