### ISSUE TITLE
Systemet restarter

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#250]
pipeline is not healthy, will restart system: Nordisk EPUB til NLBPUB

Skjer ganske ofte, og det tar ganske lang tid å restarte. Økte pipeline 2 proc til 8 for en tid siden, vet ikke om det har noe å si, men måtte det for å få pipeline til å kjøre skikkelig.

**Comment by josteinaj** [comment]
Kan være relatert til #251

**Comment by espso** [comment]
Jeg har prøvd meg på å øke timeouten, så får vi se hvordan det går. Jeg tror det blir kontraproduktivt hvis systemet må restarte hvis en produksjon er treig, men må fortsatt vente på at produksjonen skal bli ferdig før restart.

**Comment by espso** [comment]
Tror ikke dette lenger er et problem med høyere timeout på pipelines.
