### ISSUE TITLE
Sikre at all MathML blir plukket opp

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#254]
Kan ha noe med prefix å gjøre. har i alle fall sett en bok der systemet ikke detekterer math, usikker på hvorfor.

**Comment by josteinaj** [comment]
Gjelder dette validering ved mottakskontroll?

**Comment by espso** [comment]
Gjelder mottak og transformering. 

https://github.com/nlbdev/produksjonssystem/blob/master/produksjonssystem/core/utils/mathml_to_text.py#L40 

Noen denne ikke finner, skal sjekke hva det er.

**Comment by espso** [comment]
Trodde det var feil i systemet, er ikke feil i systemet.
