### ISSUE TITLE
MathML til verbal matte: hente språk fra parent

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#255]
Hvis MathML ikke har språktag slik vi ønsker at det skal ha, hent språk fra parent element.

Manglende språk = norsk.

**Comment by josteinaj** [comment]
Forslag til XPath: `(ancestor-or-self::*/@xml:lang)[last()]`.

**Comment by espso** [comment]
Gjorde det på en annen måte, fungerer nå.
