### ISSUE TITLE
Feil i epubcheck, dobbel contributor

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#258]
Eks. bok som feiler i epubcheck: 580049

ERROR(RSC-005): ..azi1ls7q/380049.epub/EPUB/package.opf(20,48): Error while parsing file: Duplicate 'contributor-700-3'
ERROR(RSC-005): ..azi1ls7q/380049.epub/EPUB/package.opf(25,48): Error while parsing file: Duplicate 'contributor-700-3'

API sier valid katalogpost
https://api.nlb.no:443/v1/editions/580049/metadata-validation-report?format=json&level=warning

Dobbel 700-3 BAHR
```
        <dc:contributor id="contributor-700-3">Advokatfirmaet BAHR</dc:contributor> <!-- Bibliofil@380049 *710 -->
        <meta property="nlbbib:bibliofil-id" refines="#contributor-700-3">22219500</meta> <!-- Bibliofil@380049 *710$_ -->
        <meta property="nlbbib:bibliofil-id" refines="#contributor-700-3">18709000</meta> <!-- Bibliofil@380049 *710$_ -->
        <meta property="nlbbib:bibliofil-id" refines="#contributor-700-3">22219500</meta> <!-- Bibliofil@380049 *710$_ -->
        <meta property="nlbbib:bibliofil-id" refines="#contributor-700-3">18709000</meta> <!-- Bibliofil@380049 *710$_ -->
        <dc:contributor id="contributor-700-3">BAHR</dc:contributor> <!-- Bibliofil@380049 *710 -->
```

**Comment by espso** [comment]
I denne utgaven er det lagt til 2x BAHR som trolig er en feil, se http://websok.nlb.no/cgi-bin/sru?version=1.2&operation=searchRetrieve&recordSchema=bibliofilmarcnoholdings&query=bibliofil.tittelnummer=380049 

Men en utgave kan vel ha to korporasjoner som bidragsytere?

**Comment by josteinaj** [comment]
Ja dette er rart. De skal få IDer nummerert som dette:

contributor-700-1
contributor-700-2
contributor-700-3
contributor-700-4

Det ser ut som det ligger som 710 og ikke 700:

```
*710  $aAdvokatfirmaet BAHR$0(NO-TrBIB)1523345891527$4ctb$_22219500
*710  $aBAHR$_18709000
```

Jeg ser det er en feil i konverteringen som brukte contributor-700 selv om det ligger i 710.

Fikset i:
https://github.com/nlbdev/normarc/commit/6469f8b24f86943c6c0174ef2db0a3759cb7303f
https://github.com/nlbdev/bibliofil-interface/commit/b3625133a1bc6e5b6a1516b6da54352cc187f20b

Skal få det i drift snart.

**Comment by josteinaj** [comment]
Dette skal virke nå. Hvis det kommer nye feilmeldinger om dette: prøv å trigge innsetting av metadata på nytt.
