### ISSUE TITLE
Fikse trigging, det ser ut som det blir en propp hvis bøker tar for lang tid å gå gjennom

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#273]
Enkelte bøker blir prøvet på nytt hele tiden. Se for eksempel nordic-epub-to-nlbpub. Andre produksjoner som ikke er ferdig blir stående.

Jeg tror (?) løsningen er å endre autotrigget køen til en sist inn først ut i stedet for sist inn sist ut.

**Comment by josteinaj** [comment]
Jeg tror vi har prøvd flere varianter nå. First-in-first-out, first-in-last-out, og tilfeldig rekkefølge. Jeg lurer på om vi er kommet dit at vi trenger en enkel database. Der kan vi lagre status for konverteringer og sørge for at systemet prøver alle bøker før den prøver feilede på nytt. Det vil også gjøre det enklere å lagre når ting ble trigget, hvor i køen ting ligger i tilfeller systemet starter på nytt, og ting som er nyttige for APIet, som hvor rapporter ligger lagret, sist status for en konvertering, osv.

Vi kan prate om det i et datamøte.

**Comment by espso** [comment]
Midlertidig fiks på plass som går gjennom alle, men langsiktig enig i det du sier om at vi kan få gjort dette på en litt mer ordentlig måte.
