### ISSUE TITLE
Lage en sjekk for om boka er ferdig kopiert

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#274]
Vi opplever at det i en del tilfeller mangler filer. Dette kan skyldes manuell, eller automatisk kopiering av filer.

Foreslår en enkel sjekk men en liste over filer som skal kopieres, og når ferdig, sjekk at det er de samme filene som er blitt kopiert.

Se filesystem.py

**Comment by espso** [comment]
Gjør et forsøk nå på å gi en advarsel hvis det ser ut som ikke alle filer er blitt kopiert. Så får vi se hvordan det går

**Comment by josteinaj** [comment]
I tillegg kunne det hjulpet å kopiere til et temp-mappe som ligger på samme server først, og så flytte hele mappen derifra i én operasjon. I så fall må vi definere egne temp-mapper for hver server.

**Comment by josteinaj** [comment]
@espso bør vi beholde denne saken åpen eller kan vi lukke den?

**Comment by espso** [comment]
Tror ikke det er noe problem nå
