### ISSUE TITLE
Ikke send rapporter for gamle katalogposter med feil

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#277]
Forslag fra @josteinaj .
Hvis katalogposten er eldre enn et år gammel, ikke send rapport til Slack eller e-post. De blir prøvd på nytt mye, fordi de aldri er blitt slettet.

**Comment by josteinaj** [comment]
Fikset i cdce83b5aa2dfc46f538ff9cc946181048312111.
