### ISSUE TITLE
Fjerne sidenummer for tidsskrift

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#278]
Denne funksjonaliteten ivaretas i dag av nlb-script. @usama49 ønsker å flytte dette til produksjonssystem. Skal kun gjelde tidsskrift produsert i formatet DTBook.

**Comment by josteinaj** [comment]
Ok. Kan baseres på om det står magazine=true i metadata.

**Comment by josteinaj** [comment]
…og det skal vel kun gjelde for DTBook
