### ISSUE TITLE
Dagsrapport produseres kun en gang etter restart

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#279]
Disse er nå fikset, så det kunne kanskje vært nyttig på kort sikt før vi får på plass noe bedre. Men av en eller annen grunn så sendes de kun en gang og så stopper.

**Comment by espso** [comment]
Mulig dette gjør at systemet ikke restarter riktig. Må fikses.

**Comment by espso** [comment]
Skal nå være i orden. Implementert slik at den ser bort i fra noen unødvendige rapporter og har en timeout på 10 min per rapport.

**Comment by espso** [comment]
Reåpner denne, fortsatt et problem med at det er noe som tar evigheter, og timeouten som er lagt inn fungerer ikke skikkelig. Dagsrapporter kan fjernes hvis det ikke brukes.

**Comment by josteinaj** [comment]
Ja kanskje enklest å fjerne dagsrapporter inntil videre? Kommentere ut der dagsrapporttråden startes og stoppes? Så ser vi om noen sier ifra om at de savner dem.
