### ISSUE TITLE
Oppdatere maler for lydbøker

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#280]
- [x] Oppdatere info om åndsverksloven (Vi bruker feil paragaf i lydbokavtalen. § 17 a skal erstattes med § 55, dette gjelder muligens flere formater)
- [x] fjern ISBN-nummer (dette er noe vi trolig setter inn automatisk)
- [x] boka er på X nivåer - generere dette tallet automatisk
- [x] fjerne overskriften "om den tilrettelagte utgava" - flytte innholdet fra dette kapittelet til slutten av kapittelet "om boka"

@espso håper det er ok om jeg setter deg på denne?

**Comment by espso** [comment]
Per sine XSLT-er er hakket vanskeligere å forstå seg på enn dine @josteinaj... For TTS bøker er det den siste lydbokavtalen som settes inn.

**Comment by josteinaj** [comment]
Jeg kan sikkert se på det jeg, men det får blir senere i så fall.

Per sine XSLTer burde vi skrevet på nytt egentlig så de blir litt enklere. Slått sammen til én fil blant annet.

**Comment by espso** [comment]
Jeg kan sikkert fikse en del av det neste uke.
