### ISSUE TITLE
Bilder i TOC/innholdsfortegnelse forsvinner mellom master/epub og NLBPUB

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#287]
Ved feil hvor det er manglende bildefiler (typisk referenced resource (...)\abc.jpg could not be found in the EPUB) ser det ut til å gjelde utelukkende bilder som er i TOC / innholdsfortegnelsen. 

Disse bildene blir borte mellom master/epub og NLBPUB, både fra filmappe og fra package.opf. 

Oppdages som regel først i validering i prepare-for-ebook.

Gjelder foreløpig følgende bøker:
566474 (fikset manuelt)
566257 (på vei gjennom prodsys på nytt men forventer samme resultat)
566597 
580038

---

Avhenger av: https://github.com/nlbdev/nlbdev/issues/261

**Comment by josteinaj** [comment]
Jeg har filesøkt litt her, og det skjer når Pipeline 2 konverterer fra EPUB til HTML med det nordiske skriptet. Men jeg lurer på om selve feilen ligger i [html-utils](https://github.com/daisy/pipeline-modules/blob/master/common/html-utils/src/main/resources/xml/xproc/html-to-fileset.xpl) i Pipeline 2 (ikke det nordiske skriptet). Jeg undersøker videre.

**Comment by josteinaj** [comment]
Jeg har fikset feilen i koden til Pipeline 2 her:
https://github.com/daisy/pipeline-modules/pull/28

Når dette kommer med i en ny versjon av Pipeline 2 så kan jeg inkludere det i en ny versjon av de nordiske skriptene, og deretter sette det i drift hos oss.

Problemer er altså at i innholdsfortegnelsen så ligger `<m:math altimg="…"` inni en `<a href="…"> … </a>`. Hadde det ikke vært pakket inn i en lenke så hadde det blitt plukket opp.

Hvis bøkene ikke haster så foreslår jeg at de blir liggende til en ny versjon blir lansert.

Bøker som haster kan vi fikse manuelt inntil videre.

**Comment by josteinaj** [comment]
Den nye versjonen av validatoren skal inneholde denne fiksen: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/500

**Comment by josteinaj** [comment]
Jeg byttet til nyeste Pipeline 2-baserte versjon av nordic-epub3-dtbook-migrator for en uke eller to siden. Så antageligvis er dette fikset nå.
