### ISSUE TITLE
Nedlasting av aviser fra FTP - eventuelt unngå bruk av FTP

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#288]
Avisfeeder lastes fra Schibsted over FTP til NLBs FTP-server. Nedlasting skjer derifra via et skript som kjører på en av TTS-serverne, men det ville trolig gitt mer mening, og vært enklere å vedlikeholde, dersom vi gjorde det i produksjonssystemet.

**Comment by josteinaj** [comment]
Eller kanskje heller montere opp mappen med avisfeeder.

**Comment by usama49** [comment]
NB vil ha vi skal bruke FTP i stedet av tilgang til FTP-server. FTP script er på doker, derfor lukker saken.
