### ISSUE TITLE
Tidsskriftproduksjon stanser grunnet valideringsfeil (DTBook)

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#290]
I skrivende stund feiler i overkant av 10 tidsskrift i nlbpub-to-tts-dtbook hvor alle feiler validering med samme feilmelding, inkl. de fleste i samme posisjon eller noenlunde samme område (199:41) og 205:41 er gjengangere.

Eksempel:

`[filnavn].xml:**199:41: error: element "h2" not allowed here**; expected the element end-tag, text or element "a", "abbr", "acronym", "address", "annoref", "annotation", "author", "bdo", "blockquote", "br", "byline", "cite", "code", "dateline", "dfn", "div", "dl", "em", "epigraph", "img", "imggroup", "kbd", "line", "linegroup", "list", "note", "noteref", "ns:math", "p", "pagenum", "poem", "prodnote", "q", "samp", "sent", "sidebar", "span", "strong", "sub", "sup", "table" or "w" (with xmlns:ns="http://www.w3.org/1998/Math/MathML")`

Tidsskrift som feiler p.t.:
558282542020
558282552020
558282562020
558282582020
558284182020
558285182020
558286112020
558287192020
558289092020
558294562020
558294572020
558294592020
558294602020
561982112020

**Comment by josteinaj** [comment]
```
<level1 id="c1" class="jacketcopy">
         
         <prodnote id="c2" class="frontcover" render="optional">
            
            <h2 id="frontcover-heading">Hjemmet</h2>
            
            <imggroup><img alt="" src="images/cover.jpg" id="img_2"/>
               
               
            </imggroup>
            
         </prodnote>
         
      </level1>
```

Dette er fra den midlertidige fila som blir validert. Her ligger det en h2 inni prodnote. h2 er bare lov rett inni level2.

**Comment by josteinaj** [comment]
Fikset i ec7c5c4e42421349cdac80b6ced849aa06e8a744
