### ISSUE TITLE
I EPUB til innlesing så endres namespace prefix fra epub til ns0

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#291]
Dvs at det står `ns0:type` i stedet for `epub:type` over alt. Ikke alle systemet skjønner namespaces, så dette bør fikses.

**Comment by josteinaj** [comment]
@espso @GauteR kan jeg sette denne på en av dere? Denne fører til feil i Hindenburg i følge @Pinadegreit.

**Comment by espso** [comment]
@josteinaj ns0 blir satt inn i pipeline2 skriptet nordic epub 3 to Nordic EPUB3 to HTML5.

Alternativ 1: løses der det er, altså i pipeline
Alternativ 2: hack, bytte namespace ns0:type tilbake til epub:type

**Comment by josteinaj** [comment]
Hvis det skjer i Pipeline 2 så er det enklere med en hack tror jeg.

**Comment by espso** [comment]
Ser ut som det skjer i Hindenburg også, hvis input er epub:type, blir output html ns0:type. 

Er det noen grunn til at vi ikke kan fjerne "epub:type="pagebreak"" her før boka blir konvertert til NLBPUB?

<span class="page-normal" epub:type="pagebreak" id="page-9" title="9"/>

Da blir output i NLBPUB

<span class="page-normal" id="page-9" title="9"></span>

i stedet for:

<span class="page-normal" ns0:type="pagebreak" id="page-9" title="9">

Jeg har ikke lest nøye gjennom epub eller NLBPUB spec for om dette er lov, men får ingen umiddelbare feilmeldinger.

**Comment by josteinaj** [comment]
Vi kan ikke fjerne `epub:type="pagebreak"` dessverre. Det er en av de få tingene som faktisk fungerer i EPUB-spillere. Ved å fjerne det så blir ikke boka invalid, men boka blir dårligere.

**Comment by espso** [comment]
Oppdatering implementert, gjenåpnes hvis det dukker opp noe.
