### ISSUE TITLE
Automatisk rotasjon av log

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#292]
Burde vi implementere det? Noen ganger blir loggen gigantisk.

**Comment by josteinaj** [comment]
Ja, har tenkt det samme.

I dag så pipes alt i cronjobben til en loggfil:

```
* * * * * . ~/config/set-env.sh && CONFIG_FILE="…/produksjonssystem.yaml" ORIGINAL_ISBN_CSV="…/original-isbn.csv" BOOK_ARCHIVE_DIRS="master=$BOOK_ARCHIVE_DIR share=$DAISY202_ARCHIVE_DIR distribution=$DISTRIBUTION_ARCHIVE_DIR news=$SCHIBSTED_ARCHIVE_DIR" TRIGGER_DIR="$BOOK_ARCHIVE_TRIGGER_DIR" SLACK_CHANNEL="#…" run-one /opt/produksjonssystem/produksjonssystem/run.py >>/tmp/produksjonssystem.log 2>&1
```

En mulighet er å bruke f.eks. ```>>produksjonssystem_`date "+%Y-%m"`.log```, som ville blitt til `produksjonssystem_2020-12.log`, og år/måned ville blitt oppdatert ved neste omstart av produksjonssystemet dersom vi er inne i en ny måned.

Alternativt kunne vi konfigurert loggfila inni selve produksjonssystemet. Da finnes det garantert moduler for å rullere loggfil etter både dato og filstørrelse / antall linjer. Kanksje noe i selve `logging`-modulen.

**Comment by espso** [comment]
Jeg synes selve loggfilen i produksjonssystemet er beste løsning her. Også i løpet av en mnd blir fila veldig stor, samtidig går det jo greit å skanne gjennom.
