### ISSUE TITLE
Håndtere store antall bilder i ulike steg

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#293]
Store bøker i betydningen tallrike filer betyr treghet og timeout.
Eksempelbok er 580217 som ikke blir validert i mottakskontroll pga. "Pipeline brukte for lang tid". Boka har over 20.000 bilder.

I nordisk epub til nlbpub er bildefiler erstattet med placeholders før de kopieres inn i NLBPUB-mappa etter konvertering/sjekk er ferdig. Har vist gode resultater.

Vurdere å implementere lignende logikk på andre steder i produksjonssystemet også.

**Comment by dankri88** [comment]
Foreslår at denne gis høyere prioritet da det er en håndfull **studiebøker** (herunder bok nevnt i issuen opprinnelig) som nå har produksjonsstans pga timeout i incoming-nordic, av samme årsak.

**Comment by josteinaj** [comment]
Fikset for innkommende-nordisk i b7ddfd26ccafa357e15d81178402e0b0a8fff74c. Satt i drift i dag.
