### ISSUE TITLE
Skille ut APIet i produksjonssystemet som en egen Docker container

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#294]
Hvert produksjonssteg (pipeline) vil ha sitt eget API. Disse produksjonsstegene må registrere seg her (eventuelt så hardkoder vi de bare inn).

I første omgang innebærer dette:

- [ ] å tilby alle de samme [endepunktene som allerede finnes i produksjonssystemet](https://github.com/nlbdev/produksjonssystem/tree/master/produksjonssystem/core/endpoints)
- [ ] å videresende kallene (uendret) som de er til dagens produksjonssystem, og returnere responsen (uendret)

Deretter kan man bygge videre på dette APIet som et API mot produksjons*miljøet* vårt, og dermed inkludere andre produksjonssteg enn de som finnes i selve produksjonssystemet. I tillegg legger det til rette for at vi kan splitte opp produksjonssystemet etterhvert (nlbdev/nlbdev#166), og siden dette vil kjøre i docker swarm så gjør det oppsett mot en eventuell database enklere (https://github.com/nlbdev/produksjonssystem/issues/295).

**Comment by josteinaj** [comment]
@espso @GauteR var dere i mål med denne eller gjenstår det fortsatt noe?

**Comment by espso** [comment]
Alle kall til produksjonssystemet går nå via production-interface. Veldig enkelt satt opp som en proxy, men det er null problem å hardkode eller finne på en måte for å sende spesifikke kall til f.eks. en pipeline som er skilt ut.

**Comment by josteinaj** [comment]
Ok, supert. Da kan vi si at denne er gjort?
