### ISSUE TITLE
Bevare feilet DTBook for feilsøking

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#298]
Ved feil i validering av DTBook i steget "nlbpub-to-tts-dtbook" slettes den midlertidige xml-filen som ble forsøkt konvertert, og det genereres en logg og feilrapport/valideringsrapport.

Rapporten viser til feil i den midlertidige filen, som skiller seg fra grunnlagsfilen på mange måter. Elementer er konvertert og linjenumre er endret. Dette gjør det svært krevende å feilsøke.

Feilene er som regel små og få, og det er ugunstig å falle tilbake på å sende bok tilbake til India for småting.

Foreslår at "work in progress"-xml fila bevares dersom det er skjer en feil. Kanskje kan den eksporteres til samme mappe som rapportene forøvrig.

**Comment by josteinaj** [comment]
@espso @GauteR @usama49 har en av dere mulighet til å ta denne? Det er vel bare snakk om en linje med `os.copy(temp_xml, reportdirblabla)` et sted tenker jeg. Kun XML fila som trengs, ikke bildefiler (ellers blir det veeeldig store rapport-mapper).

**Comment by espso** [comment]
Fikset for DTbook for TTS, greit å implementere der det trengs.
