### ISSUE TITLE
sync-point-wrapper og notereferanser

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#300]
- Teste først hvordan det fungerer i Hindenburg uten å gjøre noen ting.
- Hvis det ikke fungerer bra nok, sett inn wrappere:

### Original-EPUB:

```html
<p>
    Dette er en setning.
    Se på dette<a href="#abc" class="noteref">[1]</a> ordet.
    En setning til.
    Se på fargene blå<a href="#b" class="noteref">[2]</a>,
    rød<a href="#r" class="noteref">[3]</a> og
    grønn<a href="#g" class="noteref">[4]</a>.
</p>
```

### EPUB med wrappere:

- sync-point-wrapper som span
- sett inn "Note " foran notereferanser (eller gjør vi allerede det?)
- fjerne [], () og lignende rundt notereferansen (eller gjør vi allerede det?)

```html
<p>
    <span class="sync-point-wrapper">Dette er en setning. Se på dette</span>
    <a href="#abc" class="noteref">Note 1</a>
    <span class="sync-point-wrapper"> ordet. En setning til. Se på fargene blå</span>
    <a href="#b" class="noteref">Note 2</a>
    <span class="sync-point-wrapper">, rød</span>
    <a href="#r" class="noteref">Note 3</a>
    <span class="sync-point-wrapper"> og grønn</span>
    <a href="#g" class="noteref">Note 4</a>
    <span class="sync-point-wrapper">.</span>
</p>
```

### Fotnoter lenger ned i boka:

Uendret, samme i original-EPUBen og i fikset EPUB.

```html
<aside id="abc" class="notebody">…</aside>
<aside id="b" class="notebody">…</aside>
<aside id="r" class="notebody">…</aside>
<aside id="g" class="notebody">…</aside>
```

**Comment by josteinaj** [comment]
@Pinadegreit har testet at dette ikke fungerer ut av boksen i Hindenburg, så vi må gjøre det som står over.

**Comment by josteinaj** [comment]
Dette er fikset i produksjonssystemet, men vi venter til @Pinadegreit har fått testet om det fungerer før vi lukker denne saken.

**Comment by josteinaj** [comment]
@Pinadegreit dette er en gammel sak som ikke er oppdatert på halvannet år. Har vi fortsatt problemer med notereferanser inni sync-point-wrapper?

**Comment by Pinadegreit** [comment]
Nei

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Jostein Austvik Jacobsen ***@***.***>
Sendt: Tuesday, June 21, 2022 3:09:37 PM
Til: nlbdev/produksjonssystem ***@***.***>
Kopi: Eivind Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [nlbdev/produksjonssystem] sync-point-wrapper og notereferanser (#300)


@Pinadegreit<https://nor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPinadegreit&data=05%7C01%7Ceivind.haugen%40nlb.no%7Cd7d1512a0bdd4e1c5a6808da53874c4d%7C230a92203a3d42e7b7d9a4e26afabdb3%7C0%7C0%7C637914137812292253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ATthnqqDfy2eRQI4tF9Wv9nv67uN8oMK%2FTgQGVg0KvQ%3D&reserved=0> dette er en gammel sak som ikke er oppdatert på halvannet år. Har vi fortsatt problemer med notereferanser inni sync-point-wrapper?

**Comment by josteinaj** [comment]
Flott, da lukker jeg denne :)
