### ISSUE TITLE
Avvikle steget "nordisk manuell mottakskontroll"

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#303]
Manuell mottakskontroll etter validering av nordisk-innkommende er (blitt) overflødig.

Ønsker at validerte EPUBs fra innkommende/nordisk legges automatisk over i master/EPUB.
Etter hva jeg forstår er det en reversering til hvordan det var før.

Fra Elise:

> Vi startet med denne manuelle mottakskontrollen mens vi fortsatt sjekket metadata, men dersom denne informasjonen ikke lenger er nødvendig, ser vi heller ikke hensikten med dette manuelle leddet lenger. Vi gjør en tilstrekkelig sjekk ved bruk av de verktøyene vi har tilgjengelig før nordisk-mappa, og da steget nordisk-manuell-mottakskontroll fungerer mest for å sikre at metadata er riktig og at bøkene tilfredsstiller ACE-krav (som vi allikevel ikke har noen kontroll av per dags dato), ser vi ikke noen gevinster ved å fortsette med denne tidstyven.

>Vi ønsker derfor at valide filer flyttes automatisk fra innkommende/nordisk til master/epub. Er det noen mulighet for at dette manuelle leddet kan fjernes fra produksjonslinjen?

**Comment by josteinaj** [comment]
Fjernet i af953e8fb3018c8371b4ca6bb4d7ef13bd35d156. Satt i drift i dag.
