### ISSUE TITLE
Bruk ansvarsangivelse (*245$c) for docauthor i DTBook

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#305]
Marc-taggen `*245$c` inneholder ansvarsangivelse. Dette en tekst som tilsvarer det som står på bokomslaget. Personene/aktørene i feltet er ikke lenket til autoritetsregisteret, altså må vi behandle det som et fritekstfelt.

Eksempel: ["Vestens store tenkere" (225491)](https://websok.nlb.no/cgi-bin/websok?tnr=225491)
```
*0010225491
*245 0$aVestens store tenkere$hdaisy 2.02$bfra Platon til våre dager$credigert av Trond Berg Eriksen
*511  $aBrage Talesyntese$_19209900
*700  $aAmundsen, Leiv$jn.$emedf.$_16537200
*700  $aBaune, Øyvind$emedf.$_14426500
*700  $aBrown, Keith$emedf.$_20861100
*700  $aBø-Rygg, Arnfinn$d1949-$0(NO-TrBIB)90280969$emedf.$_12903400
*700  $aDahl, Sverre$emedf.$_13556500
*700  $aEriksen, Trond Berg$d1945-$jn.$emedf.$_19806700
*700  $aEriksen, Trond Berg$d1945-$jn.$ered.$_19806700
*700  $aFøllesdal, Andreas$emedf.$_17816400
*700  $aHaga, Ånund$emedf.$_10865700
*700  $aHagtvet, Bernt$d1946-$jn.$emedf.$_19489100
*700  $aHeyerdahl, Grete Børsand$emedf.$_13182300
*700  $aKraggerud, Egil$emedf.$_11447900
*700  $aMolland, Einar$jn.$emedf.$_16426000
*700  $aRieber-Mohn, Hallvard$jn.$wRieber Mohn, Hallvard$emedf.$_15035700
*700  $aRoll-Hansen, Nils$emedf.$_13838800
*700  $aSchaanning, Espen$d1955-$wSchånning, Espen$emedf.$_13425300
*700  $aSchjelderup, Harald$emedf.$_16254100
*700  $aSjaastad, Øystein$emedf.$_13435100
*700  $aStigen, Anfinn$jn.$emedf.$_15112400
*700  $aStorheim, Eivind$emedf.$_12100400
*700  $aStrømholm, Per$emedf.$_12387200
*700  $aSvendsen, Paulus$emedf.$_11428800
*700  $aTjønneland, Eivind$d1956-$emedf.$_19774800
*700  $aTranøy, Knut Erik$jn.$emedf.$_16419600
*700  $aVestre, Bernt$jn.$emedf.$_14815100
*700  $aWaage, Peter Normann$jn.$wWåge, Peter Normann$emedf.$_15087000
*700  $aYstad, Vigdis$jn.$emedf.$_16484800
*700  $aØsterberg, Dag$emedf.$_11488900
^
```

Her er det 27 forfattere og en redaktør i `*700`, og en innleser i `*511`. Ansvarsangivelsen står i `245$c` og `*001` inneholder boknummeret. Redaktøren er i dette tilfellet også en av forfatterne.

På bokomslaget blir det litt voldsomt å skulle vise alle disse forfatterne. Det greieste er å vise den samme ansvarsangivelsen som på det opprinnelige bokomslaget. Hvis vi henter ut `*245$c` så kan vi bruke dette feltet når vi genererer nye bokomslag. Den kan også brukes for eksempel på hjemmesiden for å vise en kortfattet verson av ansvarsangivelsen.

Avhenger av: https://github.com/nlbdev/normarc/issues/18
Relatert: https://github.com/nlbdev/bibliofil-interface/issues/36
Relatert: https://github.com/nlbdev/bibliofil-validator/issues/23

**Comment by espso** [comment]
Dette skal være fikset i DTBook. Mulig det er noe å se på i EPUB, men venter trolig til Jostein er tilbake.

**Comment by josteinaj** [comment]
docauthor finnes ikke i EPUB. Men det hadde vært fint om EPUB-lesere brukte `responsibilityStatement` i opplisting av bøker osv. Jeg vet ikke hva som er den beste måten å få til det er.
