### ISSUE TITLE
Lage pipeline for Latex

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#315]
Lage en egen pipeline for bøker produsert som Latex. Dette er kanskje godt egnet for å vise frem matte og det er i alle fall noen som vil ha det. @GauteR har klargjør endepunkt på API-internal som returnerer Latex basert på en xhtml fil.

inn:
utgave-klargjort/e-bok

ut:
utgave-ut/LATEX

Ikke automatisk trigging av manglende bøker for denne. Distribusjon av dette gjøres på E-post, i alle fall i første omgang.

**Comment by GauteR** [comment]
Endepunktet POST `/v1/systems/latex/html` tar imot XHTML i direkte - ikke som fil, men som streng. F. eks. 

```bash
curl -X 'POST' \
  'https://api.dev.nlb.no:443/v1/systems/latex/html' \
  -H 'accept: application/json' \
  -H 'Content-Type: text/xml' \
  -d '<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>...</html>'
```

XHTML strengen må inneholde:

- metadata
- XHTML i sin helhet (som en stor fil)
- MathML som den oppstår i `master/NLBPUB`

Så å komme unn på `utgave-klargjort/e-bok` er kanskje for sent i prosessen, for der er MathML tatt vekk. Den må inn på det steget hvor MathML blir fjernet.

**Comment by GauteR** [comment]
Inngår i: https://github.com/nlbdev/nlbdev/issues/257

**Comment by josteinaj** [comment]
- [ ] https://github.com/nlbdev/service-latex/issues/1
