### ISSUE TITLE
Tidsskrift stopper i metadatasteg: finner ikke katalogpost

### ISSUE THREAD

**Issue by dankri88** [nlbdev/produksjonssystem#323]
Tidsskrift stopper i metadatasteg, ser ut som det gjøres et feil oppslag på katalogpost. Det slås opp på hele det 12-sifrede tidsskriftnummeret men det skal vel oppfattes at det er et tidsskrift og deretter kun slås opp på de første 6.

Vedlagt loggeksempel fra hhv feilende og suksess. Virker som noe har gått galt fra og med september. 
[feilende tidsskrift, Hjemmet uke 42.txt](https://github.com/nlbdev/produksjonssystem/files/7203027/log.txt)
[vellykket tidsskrift, Hjemmet uke 41](https://github.com/nlbdev/produksjonssystem/files/7217279/log.txt)

**Comment by josteinaj** [comment]
Feilen er på grunn av: https://github.com/nlbdev/api-internal/issues/239

Har blitt løst med en workaround her: https://github.com/nlbdev/produksjonssystem/commit/ac4a4ad1a3100b2dd07b3a60f1de0fed38ff9223
