### ISSUE TITLE
/editions/.../reports/... Legge til ulike visningstyper for logg-filer

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#326]
På samme måte som `metadata-validation-report` tilby i HTML, JSON og CSV etter valg i format kallet, dvs.

`/editions/{editionId}/reports/{jobId}?format=html|json|csv`

Bør være på plass innen vi legger om til Quickbase fremfor epost for å jobbe med feilmeldinger.

Kan enten løses i produksjonssystemet eller API-et (se egen sak i api-internal https://github.com/nlbdev/api-internal/issues/236)

**Comment by josteinaj** [comment]
Jeg har løst dette ved at loggfiler alltid er plain text (log.txt) og rapporter alltid er HTML (email.html).

- `/editions/<edition_id>/reports/`: liste over alle jobber
- `/editions/<edition_id>/logs/`: liste over alle jobber (samme som over)
- `/editions/<edition_id>/reports/<job_id>`: HTML-rapport for job_id
- `/editions/<edition_id>/logs/<job_id>`: detaljert loggfil for job_id (text/plain)

HTML-rapporten og den detaljerte loggfila har ingen struktur som gjør at det gir mening å vise de som JSON eller CSV.

**Comment by josteinaj** [comment]
job_id = "last" er forresten nå den nyeste rapporten, i tilfelle man vil lenke til den. Men det kan være hvilken som helst pipeline.

**Comment by josteinaj** [comment]
Følges opp i https://github.com/nlbdev/produksjonssystem/issues/245.
