### ISSUE TITLE
Mulighet til å skille på h1 og h2 vha. understreking

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#335]
Så på å løse dette vha. CSS, men det viste seg å ikke være så lett:

Mail fra Dawn i Statped:

> Vi ønsker at default h1 skal være understreket, men understrekingen må være like lang og i samme posisjon som den lengste linjen med tekst i overskriften.
> Når overskriften er lang deles den på flere linjer og det er umulig å vite hvor lang den lengste linjen blir.
> I tillegg ønsker vi ikke at den første linjen skal være lengst når en overskrift går over flere linjer.

> Her er et eksempel på ok oppsett:
```
     *Kapittel #1:
     *Markedsføring i teori
     og praksis
     cccccccccccccccccccccc
```

Man får lagt til dette i CSS, men får ikke angitt lengden (såvidt jeg vet). Det kreves mer tilpasning.
![image](https://user-images.githubusercontent.com/19590971/146002520-768cdda5-7fcd-4131-9802-13d3ccc7f229.png)

---

Dawn og Tage ønsker statusoppdatering når/hvis dette blir implementert, evt. legges på is.

**Comment by josteinaj** [comment]
> I tillegg ønsker vi ikke at den første linjen skal være lengst når en overskrift går over flere linjer.

Dette er nok ikke praktisk mulig dessverre.

Denne `&::after`-blokken må være noe Statped har lagt til? For å få understrek som er like lang som teksten kan de legge inn igjen `border-bottom: ⠤;` som de har kommentert ut.

**Comment by josteinaj** [comment]
…og egentlig så skal det vel være `border-bottom: ⠉;`, ikke `border-bottom: ⠤;`.

**Comment by josteinaj** [comment]
@GauteR var det her det var kommet en løsning?

**Comment by josteinaj** [comment]
@GauteR var det her det var kommet en løsning? 🙂 Lukke?

**Comment by GauteR** [comment]
De hadde løst det selv, ja.
