### ISSUE TITLE
For innlesing: flytte sidetall ut av avsnitt

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#341]
Hør med @Pinadegreit om noe er uklart.

**Comment by josteinaj** [comment]
**Regex:**

Find:
```regex
(<p[ >].*?)<span([^>]*epub:type="[^"]*pagebreak.*?)</span[^>]*>(.*?</p[^>]*>)
```

Replace with:
```regex
<div$2</div>\n$1$3
```

XPath:
```xpath
//p[span[tokenize(@epub:type, '\s+') = 'pagebreak']]
```

Skjermbilde:
![Skjermdump fra 2022-01-18 23-32-24](https://user-images.githubusercontent.com/295481/150029388-b6ed225f-4dd2-4dca-bf2b-ac47a6fc0e4c.png)

Dette gjør om sideskiftet fra span til div, og flytter det ut foran `<p>`-elementet. Ved å flytte det til før `<p>`-elementet og ikke etter, så kommer sideskiftene i riktig rekkefølge i tilfelle det er flere sideskift inni samme avsnitt.

---

Alternativt, om man foretrekker å flytte sideskiftene til _etter_ `<p>`-elementet:

Replace:
```regex
$1$3\n<div$2</div>
```

For å sjekke om det finnes flere sideskift inni samme avsnitt, søk etter:

XPath:
```xpath
//p[count(span[tokenize(@epub:type, '\s+') = 'pagebreak']) gt 1]
```

Bruk XPath-søkefelt øverst i Oxygen, eller fyll inn "XPath" i søk-og-erstatt-boksen, og bruk regexen `.*` i "Find".

**Comment by josteinaj** [comment]
@Pinadegreit her er forslag til regex-løsning.

**Comment by Pinadegreit** [comment]
Takker jeg ser på det i morgen.
________________________________

**Comment by Pinadegreit** [comment]
Hei

Ser ikke ut til at regexen treffer helt «no strings found». Legger ved en eksempel fil.

Mvh

Eivind

**Comment by Pinadegreit** [comment]
Hei Jostein

Den fungerer på EPuber som ikke har vært gjennom Hindenburg.

Eivind

From: Eivind Haugen
Sent: onsdag 19. januar 2022 14.14
To: nlbdev/produksjonssystem ***@***.***>
Subject: RE: [nlbdev/produksjonssystem] For innlesing: flytte sidetall ut av avsnitt (Issue #341)

Hei

Ser ikke ut til at regexen treffer helt «no strings found». Legger ved en eksempel fil.

Mvh

Eivind

**Comment by Pinadegreit** [comment]
Ok. Kan du sende meg eksempelet på e-post eller i Teams? Ser ut til at det forsvant når du svarte til Github.



Med vennlig hilsen

[NLB]

Jostein Austvik Jacobsen
Seniorutvikler / Senior Developer
Norsk lyd- og blindeskriftbibliotek /
Norwegian Library of Talking Books and Braille
https://www.nlb.no/


________________________________
Fra: Eivind Haugen ***@***.***>
Sendt: torsdag 20. januar 2022 12:42
Til: nlbdev/produksjonssystem ***@***.***>; Jostein Austvik Jacobsen ***@***.***>
Emne: RE: [nlbdev/produksjonssystem] For innlesing: flytte sidetall ut av avsnitt (Issue #341)


Hei Jostein



Den fungerer på EPuber som ikke har vært gjennom Hindenburg.



Eivind



From: Eivind Haugen
Sent: onsdag 19. januar 2022 14.14
To: nlbdev/produksjonssystem ***@***.***>
Subject: RE: [nlbdev/produksjonssystem] For innlesing: flytte sidetall ut av avsnitt (Issue #341)



Hei



Ser ikke ut til at regexen treffer helt «no strings found». Legger ved en eksempel fil.



Mvh



Eivind

**Comment by josteinaj** [comment]
**Regex for DAISY 2.02:**

Find:
```regex
(<p[ >].*?)<span([^>]*class="[^"]*page-.*?)</span[^>]*>(.*?</p[^>]*>)
```

Replace with:
```regex
<span$2</span>\n$1$3
```

XPath:
```xpath
//p[span[tokenize(@class, '\s+') = ('page-front', 'page-normal', 'page-special')]]
```

I DAISY 2.02 skal sideskift alltid være span, så dette endrer ikke til div. Sideskiftet blir flyttet ut foran `<p>`-elementet. Ved å flytte det til før `<p>`-elementet og ikke etter, så kommer sideskiftene i riktig rekkefølge i tilfelle det er flere sideskift inni samme avsnitt.

---

Alternativt, om man foretrekker å flytte sideskiftene til _etter_ `<p>`-elementet:

Replace:
```regex
$1$3\n<span$2</span>
```

For å sjekke om det finnes flere sideskift inni samme avsnitt, søk etter:

XPath:
```xpath
//p[count(span[tokenize(@class, '\s+') = ('page-front', 'page-normal', 'page-special')]) gt 1]
```

Bruk XPath-søkefelt øverst i Oxygen, eller fyll inn "XPath" i søk-og-erstatt-boksen, og bruk regexen `.*` i "Find".

**Comment by josteinaj** [comment]
**Regex som skal virke både med valid EPUB og med Hindi-prosjektfil:**

Find:
```regex
(<p[ >].*?)<span([^>]*epub:type="[^"]*pagebreak.*?)(/>|</span[^>]*>)(.*?</p[^>]*>)
```

Replace with:
```regex
<div$2</div>\n$1$4
```

XPath:
```xpath
//p[span[tokenize(@epub:type, '\s+') = 'pagebreak']]
```

Dette gjør om sideskiftet fra span til div, og flytter det ut foran `<p>`-elementet. Ved å flytte det til før `<p>`-elementet og ikke etter, så kommer sideskiftene i riktig rekkefølge i tilfelle det er flere sideskift inni samme avsnitt.

---

Alternativt, om man foretrekker å flytte sideskiftene til _etter_ `<p>`-elementet:

Replace:
```regex
$1$4\n<div$2</div>
```

For å sjekke om det finnes flere sideskift inni samme avsnitt, søk etter:

XPath:
```xpath
//p[count(span[tokenize(@epub:type, '\s+') = 'pagebreak']) gt 1]
```

Bruk XPath-søkefelt øverst i Oxygen, eller fyll inn "XPath" i søk-og-erstatt-boksen, og bruk regexen `.*` i "Find".

**Comment by josteinaj** [comment]
@nlbdev/utviklere kan jeg ha et lite arbeidsmøte med minst en av dere, hvor vi fikser denne saken? Det er en liten sak som jeg ikke har rukket å fikse men som er viktig for innlesing. Og det er en fin mulighet til å lære seg litt XSLT. Vi kommer til å ha XSLT i systemene våre i lang tid fremover, så det er fint om flere har har litt grunnleggende kjennskap til det.

**Comment by josteinaj** [comment]
@Pinadegreit var det sånn at dette var fikset i Hindenburg nå og ikke er nødvendig lenger? Eller vil du helst at vi fortsatt flytter sidetall ut av avsnitt?

**Comment by RuneRismo** [comment]
@josteinaj Jeg blir gjerne med på et arbeidsmøte for å lære hvis det fortsatt er aktuelt.

**Comment by Pinadegreit** [comment]
Dette er fikset. God løsning uten å flytte sidetall i tekst.

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: RuneRismo ***@***.***>
Sendt: Wednesday, March 30, 2022 12:38:49 PM
Til: nlbdev/produksjonssystem ***@***.***>
Kopi: Eivind Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [nlbdev/produksjonssystem] For innlesing: flytte sidetall ut av avsnitt (Issue #341)


@josteinaj<https://nor01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjosteinaj&data=04%7C01%7Ceivind.haugen%40nlb.no%7C0cd76a6f5138463b564608da12397b09%7C230a92203a3d42e7b7d9a4e26afabdb3%7C0%7C0%7C637842335330691606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=dlhr7ZB%2Fz9NJbMEEH60ao5NA2uucwfS2wFK6T%2F6UavA%3D&reserved=0> Jeg blir gjerne med på et arbeidsmøte for å lære hvis det fortsatt er aktuelt.

**Comment by josteinaj** [comment]
Ok, flott, da lukker jeg denne :+1:
