### ISSUE TITLE
Sende mail til KABB for kun KABB bøker

### ISSUE THREAD

**Issue by espso** [nlbdev/produksjonssystem#343]
KABB kan ikke få feilmeldinger for alle bøker. Det gjelder forsåvidt Statped også.

I denne omgangen så er det viktig for lydbok-til-validering.

Eventuelt løse ved å gi Kabb og Statped tilgang til produksjonsverktøyet:
- https://github.com/nlbdev/produksjonsverktoy/issues/11

**Comment by josteinaj** [comment]
Jeg tror vi så på dette tidligere for Statped og fant ut at det var vanskelig å få til? Eller kanskje ikke? Kanskje det var rapporter i Quickbase vi så på.

Produksjonssystem-GUI kan kanskje brukes for å løse dette også. (CC @GauteR)

**Comment by josteinaj** [comment]
Produksjonsverktøy ja, bedre navn :+1:.

**Comment by espso** [comment]
Tror det vil ta litt for lang tid i første omgang, men absolutt gir mening på sikt. 

Det kan da ikke være så vanskelig å sende en e-post til none folk dersom det er en KABB bok...?

**Comment by josteinaj** [comment]
Enig, skulle tro det ikke var så vanskelig. Jeg blander sikkert med en annen sak.

Vil dette også gjøre at de får rapporter fra temp-skript på e-post?

**Comment by josteinaj** [comment]
Dette er kanskje løst allerede. Vi lukker inntil videre.
