### ISSUE TITLE
Nytt steg: flytte bøker fra innkommende/Statped-NLBPUB til master/NLBPUB

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#347]
Statped har behov for å redigere bøkene i master/NLBPUB. Uten denne muligheten så stopper all produksjonen deres. De bruker i dag en egen versjon av produksjonssystemet sånn at ikke alt stopper helt opp.

Jeg foreslår at vi lager et enkelt steg som fanger opp bøker som legges i innkommende/Statped-NLBPUB, og flytter bøkene til master/NLBPUB (+ slette gammel bok hvis det ligger en tidligere versjon der fra før).

**Comment by espso** [comment]
Det høres jo ut som en grei nok sak. Skal det valideres eller noe sånt?

**Comment by josteinaj** [comment]
Ja, bør være greit, må bare sette av tid og gjøre det.

Det skal ikke valideres nei. Det er bare en workaround som erstatning for at de ikke lenger har skrivetilgang til master/NLBPUB.
