### ISSUE TITLE
Oppgradering av diverse Statped-kode

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#348]
ZIP-fil fra Tage med endringer: [upgrade.zip](https://github.com/nlbdev/produksjonssystem/files/8079447/upgrade.zip)

Det ser ut til å gjelde disse stegene, inkludert to XSLTer:
- nlbpub-to-docx
- nlbpub-to-pef
- prepare-for-braille
- prepare-for-docx

@espso er det ok om jeg setter deg på denne?

**Comment by espso** [comment]
Den er god

**Comment by josteinaj** [comment]
Jeg har ukritisk lagt endringene over fra ZIP-filen til en egen branch (statped-dev) og laget en pull request her: https://github.com/nlbdev/produksjonssystem/pull/351
