### ISSUE TITLE
Eksponere pipeline produksjonsrapporter gjennom rapport endepunkter

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#352]
Vi får nå generert produksjonsrapporter for pipeline gjennom TTS-skriptet https://github.com/nlbdev/ParallelAutoTTS/issues/1
Det hadde vært fint å kunne eksponere disse via rapport endepunkter, slik at de kan hentes opp i eksterne programmer (les: Quickbase)

Ser for meg at man gjør kall mot:
GET `/v1/editions/123456/tts-production/log` eller lignende for å hente ut logg-filen, som da henter `123456.log` i "logger"-mappen på TTS serveren

**Comment by josteinaj** [comment]
Jeg laget denne nå:

- https://github.com/nlbdev/production-interface/issues/5

Kan vi lukke denne saken og heller følge det opp der?
