### ISSUE TITLE
Lydbok til validering ,MTM bøker skal ha  Max filstørrelse optill 200 MB

### ISSUE THREAD

**Issue by usama49** [nlbdev/produksjonssystem#356]

**Comment by josteinaj** [comment]
Enkeltfiler opptil 200MB? Hvordan vil det virke i forskjellige avspillingssystemer? Hvordan blir det når man strømmer i Lydhør? Jeg tror det vil oppleves veldig tregt.

**Comment by usama49** [comment]
Kan være treg på noen men den er kun for MTM bøker. Der er forskjellig type lyd filer med forskjellig bitrate og sample rate. Endring med bitrate kan endre størrelsen. Hva er andre alternative?

**Comment by josteinaj** [comment]
Å splitte lydfilene er et alternativ

**Comment by usama49** [comment]
Vi har en issue for å splitte lyd fil. Hva gjør med MTM bøker for den splitting lyd er ikke på plass? @Pinadegreit Hva tenker du?

**Comment by espso** [comment]
Så vidt jeg vet støtter DOD og Lydhør range-requests, dvs trenger ikke laste ned hele filen. Det kan uansett bli problemer i DOD spillere og flere andre tilfeller, så det er ikke ønskelig å ha så store filer.

**Comment by Pinadegreit** [comment]
Jeg tenker at vi prøver med store filer, uten å dele dem.

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: espso ***@***.***>
Sendt: Friday, June 10, 2022 2:15:50 PM
Til: nlbdev/produksjonssystem ***@***.***>
Kopi: Eivind Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [nlbdev/produksjonssystem] Lydbok til validering ,MTM bøker skal ha Max filstørrelse optill 200 MB (Issue #356)


Så vidt jeg vet støtter DOD og Lydhør range-requests, dvs trenger ikke laste ned hele filen. Det kan uansett bli problemer i DOD spillere og flere andre tilfeller, så det er ikke ønskelig å ha så store filer.

**Comment by josteinaj** [comment]
Gjelder det mange bøker?

**Comment by Pinadegreit** [comment]
5% sånn ca.

Last ned Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Jostein Austvik Jacobsen ***@***.***>
Sendt: Sunday, June 12, 2022 8:13:25 PM
Til: nlbdev/produksjonssystem ***@***.***>
Kopi: Eivind Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [nlbdev/produksjonssystem] Lydbok til validering ,MTM bøker skal ha Max filstørrelse optill 200 MB (Issue #356)


Gjelder det mange bøker?

**Comment by josteinaj** [comment]
Jeg sjekket med Ingvild F hva hun tenkte om saken. Hun var skeptisk. Kan du høre med henne Eivind? Hvis dere fortsatt mener at vi bør tillate filer på 200MB etter det så gir jeg meg :)

**Comment by Pinadegreit** [comment]
Snakket med Ingvild og vi bli enige om å åpne opp for 200MB filer som et forsøk, så kan hun sjekke.

**Comment by espso** [comment]
For alle bøker eller bare MTM, og i så fall hvordan vet vi det at det er MTM?

**Comment by usama49** [comment]
Det er kun for MTM bøker. @Pinadegreit Kan du sjekke me biblitaker at det er noen tag for MTM bøker? Eller det kan sette noen Tag i bibliofil?

**Comment by josteinaj** [comment]
Relatert (men bør nok sjekke med bibliotekarer uansett):

- https://github.com/nlbdev/normarc/issues/17

**Comment by josteinaj** [comment]
@usama49 @espso dette tror jeg ble gjort? Ikke et problem lenger?

**Comment by Pinadegreit** [comment]
Dette er gjort. 😀

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Jostein Austvik Jacobsen ***@***.***>
Sendt: Monday, September 11, 2023 4:35:32 PM
Til: nlbdev/produksjonssystem ***@***.***>
Kopi: Eivind Haugen ***@***.***>; Mention ***@***.***>
Emne: Re: [nlbdev/produksjonssystem] Lydbok til validering ,MTM bøker skal ha Max filstørrelse optill 200 MB (Issue #356)


@usama49<https://github.com/usama49> @espso<https://github.com/espso> dette tror jeg ble gjort? Ikke et problem lenger?

**Comment by usama49** [comment]
nå vi har endret filstørrelse optill 200MB.  jeg lukker saken
