### ISSUE TITLE
Legge til samisk annonseringsmal for innlesing

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#357]
Se også:

- https://github.com/nlbdev/produksjonssystem/issues/358

**Comment by GauteR** [comment]
[Oversette maler.docx](https://github.com/nlbdev/produksjonssystem/files/9044576/Oversette.maler.docx)
[Oversette maler samas sbj1.docx](https://github.com/nlbdev/produksjonssystem/files/9044577/Oversette.maler.samas.sbj1.docx)

**Comment by josteinaj** [comment]
Oversettelsen mangler ", og er på [sider] sider" for bøker som har sidetall. Jeg dropper den setningen inntil videre for nord-samiske bøker.

**Comment by josteinaj** [comment]
Setningen etter "Boka er utgjeven av …", dersom boka har en originalutgave, er:

"Boka er første gang utgjeven i [årstall], dette er [utgave]. utgåva."

Denne mangler også oversettelse, så jeg dropper den.

**Comment by josteinaj** [comment]
Deretter kommer denne setningen, dersom boka er oversatt:

"Boka er første gong utgjeven på [originalspråk]. Originaltittel er [originaltittel]. Boka er omsett av [oversetter]."

Dette mangler også oversettelse, så den dropper jeg også.

**Comment by josteinaj** [comment]
"underkapittel" er i følge https://www.dinordbok.no/samisk-norsk/: "oassekapihtal".

**Comment by josteinaj** [comment]
Siden "lydbok med tekst" er "jietnagirji mas lea teaksta" så bruker jeg "mas lea" ("hvor er") for "med".

**Comment by josteinaj** [comment]
For bøker uten kapitler skriver vi "Boka er ikkje delt inn i kapittel, men består av lengre og kortare avsnitt." Men dette er ikke oversatt, så jeg fjerner det.

**Comment by josteinaj** [comment]
Høyere tallord i følge https://www.dinordbok.no/norsk-samisk/:
syv: čieža
åtte: gávcci
ni: ovcci
ti: logi
høyere tall har flere oversettelser så der bruker jeg bare tallet.

**Comment by josteinaj** [comment]
og = ja

**Comment by josteinaj** [comment]
Oversettelse mangler for sluttinformasjon:

"Du høyrde [tittel], av [forfatter]."

Statpeds sluttinformasjon vil ikke virke tror jeg, men det får de følge opp hvis de skal produsere nord-samiske bøker.

**Comment by josteinaj** [comment]
"Dárogiela girjegiela ja eaŋgalsgiela lohket dát jienat: Clara ja William."

Jeg stryker denne setningen for TTS-bøker. Det blir litt kunsting å nevne nynorsk og engelsk men ikke bokmål. Jeg antar det bare er en direkte oversettelse fra bokmålsteksten, og ikke er tilpasset samisk.

**Comment by josteinaj** [comment]
Jeg endrer forøvrig koden til å foretrekke navnet på stemmen som står som innleser i katalogen. Hvis det ikke står noe i katalogen ås brukes William, Clara, Hulda eller Biera avhengig av språkkode. Hvis det er en ukjent språkode så brukes Clara.

**Comment by josteinaj** [comment]
Statped sin opphavsrettside vil fortsatt bruke bokmål for eventuelle samiske bøker.

Kabb har ikke noen opphavsrettside.

**Comment by josteinaj** [comment]
Oppdatert XSLT ligger i git nå.

Jeg får ikke kjørt testene lokalt lenger. Jeg har en for ny Python-versjon. Håper det virker. @espso @GauteR har dere fungerende testoppsett lokalt på PCene deres?

Sikter på å sette i drift på mandag.

**Comment by GauteR** [comment]
Du får lukke saken når du føler det er tilstrekkelig testet @josteinaj - jeg har ikke fungerende testoppsett på min PC.

**Comment by josteinaj** [comment]
Så bra :+1:.

Må få fikset testoppsettet mitt lokalt, er dumt å ikke få testet.
