### ISSUE TITLE
Automatisk endre språkkoder i DTBøker som skal til TTS

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#362]
- Ikke røre `no`, `nb`, `nn` eller `en`
- alle andre språkkoder endres til `nb`

Opprinnelig ønske fra EPUB-teamet:

> Bedre håndtering av språkoppmerking av andre språk utover bokmål, nynorsk og engelsk i senere ledd i produksjonslinja. Språkoppmerking som ikke støttes i visse formater bør håndteres separat med automatisk skript som evt. Fjerner/konverterer språk som ikke støttes.

**Comment by GauteR** [comment]
Dette er en konfigurasjonssak av Pipeline på TTS-serverne. Gjøre endringer i `ttsbuilder.xml` for å si til Pipeline at den skal benytte stemmen for "Norsk Bokmål" på alle språk som ikke er `no`, `nb`, `nn `eller `en`

**Comment by GauteR** [comment]
[ttsbuilder.zip](https://github.com/nlbdev/produksjonssystem/files/9139551/ttsbuilder.zip)
Legger ved oppdatert konfig-fil for Pipeline. Skal legges inn på TTS-serverne etter sommeren. 

Samt må de samiske stemmene også installeres på de gamle serverne.
I tillegg må ny versjon av ParallelAutoTTS (med egne server-spesifikke konfig-filer) installeres.

**Comment by josteinaj** [comment]
@GauteR klarer vi å lukke denne i løpet av august, eller skal vi ta den med til neste periode?

**Comment by GauteR** [comment]
@usama49 løste denne saken i https://github.com/nlbdev/ParallelAutoTTS/issues/6
