### ISSUE TITLE
Bestille EPUB av Nord-samiske bøker

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#367]
Fra aktivitetsplanen for andre periode 2022:

> Dette gir mulighet for LMT og TTS for nord-samisk litteratur, dette vurderes i perioden. Produksjonssystemet må oppdateres (utvides) slik at vi kan produsere samisk litteratur. 
> 
> - Nye annonseringsmaler 
> - Produksjonssystem 
> 
> Kontakt: Eivind

**Comment by GauteR** [comment]
Vi har satt opp NLB-TTS6 til testing av Samisk TTS.
På denne kjører ny versjon av ParallelAutoTTS, som skal hente filer fra Quickbase-rapporten: https://dtbook.quickbase.com/db/bhh8n666n?a=q&qid=385

Det som gjenstår her er å markere bøker som "sm" eller "sme" i språk på boken på Quickbase, og så teste at de går gjennom produksjonen skikkelig.

**Comment by josteinaj** [comment]
Hvilke katalogiseringsrutiner blir endret?

**Comment by josteinaj** [comment]
aha, ok

**Comment by usama49** [comment]
Bøkene 582647, 582648, 582782  virker på pipeline GUI . TTS6 mangler lisense til Cereproc Cserver derfor bøker feiler på no lang tag.

**Comment by josteinaj** [comment]
Hvordan ligger vi an her?

**Comment by usama49** [comment]
Er i drift på TTS5

**Comment by josteinaj** [comment]
Så nå kan vi produsere samiske bøker, alt som trengs er på plass?

**Comment by usama49** [comment]
TTS 5 er manualt  og Thomas skal lage de manult. Neste uke vi skal sette i Drift på TTS 2 og TTS4 som er automatisk.

**Comment by josteinaj** [comment]
Ok supert :+1:. Da lar vi denne saken være åpen inntil videre.
