### ISSUE TITLE
Innlemme Kabb i tekstbasert produksjonslinje - Vårt Land

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#369]

**Comment by josteinaj** [comment]
Vi venter på svar fra Vårt Land. Vi trenger å vite mer om filene vi kan få.

**Comment by josteinaj** [comment]
Ammar har fått filer og er i gang med testing.

**Comment by josteinaj** [comment]
Hvordan er status her?

**Comment by usama49** [comment]
Kabb har sendt spec for DTBOOK til india. venter 2. versjon av dtbook fra India

**Comment by usama49** [comment]
den er i gang.
