### ISSUE TITLE
Make sure that all books have a language

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#38]
Several books seems to have empty xml:lang attributes and no dc:language metadata. (Also they seem to lack dc:identifier?)

**Comment by usama49** [comment]
Must have these elements at least once and must not be empty 
"dc:Language" content="no"
"dc:Date" content="YYYY-MM-DD"/>
"dc:Publisher" content="Norsk lyd- og blindeskriftbibliotek"/>
"dc:Title" content="x"

**Comment by josteinaj** [comment]
Use two-letter codes (many systems have problems with the culture part of the language). So use "nb" and "nn" instead of "nb-NO" and "nn-NO". Consider allowing "no" as well?

**Comment by josteinaj** [comment]
@usama49 Må dc:Date følge `YYYY-MM-DD` eller `YYYY`? Hva brukes den til? I Bibliofil har vi "klar for utlån" i `592$a`, og årstallet boka ble utgitt står i `260$c`. Sånn det er nå så kommer det ut som dette:

```xml
<meta property="dc:date.available">2018-01-30</meta> <!-- Bibliofil@360812 *592$a -->
<meta property="dc:date.issued">2018</meta> <!-- Bibliofil@360812 *260$c -->
```

**Comment by josteinaj** [comment]
`/dtbook/@xml:lang` skal nå være tilbake: 9d4c99ed87104284c5947651e6fe44031b4c02c1

`dc:Date` blir autogenerert: 728e4276d3f0354fd2d2a0e1daea26a6fbabd818

Tobokstavs språkkode ble fikset for en uke siden: b7b576c791b84b3765719bba0d36f6dccce13f05.

publisher (og hvordan metadata hentes ut for hver utgave separat) har det vært noen endringer med så det tror jeg også skal virke nå: 376080a4a09879b54c0b4ca57dd8a78bf9368978, 9cbaba9868487ab59dfc3e4a7b8d3d409a8c2461

@usama49 kan du sjekke om alt stemmer i de nye bøkene som blir generert i "`DTBook-til-talesyntese`"-mappa nå?

**Comment by usama49** [comment]
ny bøker kommer med riktic DC date.
takk

**Comment by josteinaj** [comment]
Supert.
