### ISSUE TITLE
Fikse XSLT: "acronym is disallowed in nordic dtbooks" - men "acronym" går fortsatt igjennom til TTS-produksjon

### ISSUE THREAD

**Issue by GauteR** [nlbdev/produksjonssystem#398]
Denne funker ikke:

`<doctitle smil:clipBegin="0:00:00" smil:clipEnd="0:00:06.925" smil:sync="true" smil:src="speechgen0001.mp3">Hvordan virker <acronym pronounce="no" title="United States of America">USAs</acronym> og <acronym pronounce="no" title="European Union">EUs</acronym> ABB-tessst, CLARA-abbtest, og Clara-abbtest?</doctitle>`

Denne funker:

`<doctitle smil:clipEnd="0:00:06.395" smil:sync="true" smil:clipBegin="0:00:00" smil:src="speechgen0001.mp3">Hvordan virker USAs og EUs ABB-tessst, CLARA-abbtest, og Clara-abbtest?</doctitle>`

https://github.com/nlbdev/produksjonssystem/blob/faf59e53347bc945a0ceb39b067f8572d07f21c5/xslt/nlbpub-to-tts-dtbook/html-to-dtbook.xsl#L773

Så tenker det er en XSLT som må fikses, så bør dette være i orden. Hvorfor den regelen som er der, ikke plukker opp disse, er uvisst.

[speechgen.zip](https://github.com/nlbdev/produksjonssystem/files/12792029/speechgen.zip)

285595 trigger IKKE feilen.
282585 trigger feilen.

**Comment by GauteR** [comment]
Mari meldte om dette.

**Comment by josteinaj** [comment]
Her er det også litt sånn prinsipielt om vi vil følge nordisk DTBook, eller bare generell DTBook. Vi kan bytte til Pipeline 2 for konvertering fra EPUB/HTML til DTBook hvis vi vil ha en generell konvertering. Den er basert på den nordiske uansett, så den er ganske lik.

**Comment by josteinaj** [comment]
@GauteR var denne lagt på is?

**Comment by Kovaogata** [comment]
Ser at denne saken ligger på is, men trenger informasjon om hvordan vi skal behandle disse produksjonene der hvor det blir et problem. Er det mulig for oss å generere ny DTBook i de tilfellene? Eller endre noe i DTBook? Klarer ikke å se forskjellen på en DTBook hvor feilen oppstår og en hvor den ikke oppstår.

**Comment by josteinaj** [comment]
Hvor i produksjonslinja er det boka stopper?

**Comment by josteinaj** [comment]
Jeg hadde et arbeidsmøte med Mari i dag. Vi fant en løsning på problemet. I definisjonen av Narrator-skriptet, så er det aktivert forkortelses-deteksjon her:

https://github.com/daisy/pipeline1/blob/5ddce3ac4058558e4cce007fa786ca8dc209c3d9/scripts/create_distribute/dtb/Narrator-DtbookToDaisy.taskScript#L192-L195

Vi satte denne til `false` på TTS1 og da ble det ikke noen akronym-oppmerking lenger :+1::

```xml
		<parameter>
			<name>doAbbrAcronymDetection</name>
			<value>true</value>
		</parameter>
```

@GauteR Mari skal teste litt mer for å være sikker på at problemet er løst først, men når det er løst så bør dette inn på alle serverne, og også i git, sånn at vi husker det til en eventuell reinstallasjon senere.
