### ISSUE TITLE
Bedre håndtering av titlepage og halftitlepage i DTBook

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#42]
Forslag fra Mari:

Regel for class=halftitlepage og for class=titlepage:
- Fjern tekststrenger som allerede finnes i `<docauthor>` og `<doctitle>` …
- Og fjern hele `<level1>` dersom tom
- Og fjern class-atributtet dersom det ikke er tomt (fordi forlagsnavnet og sidetall står igjen)

**Comment by josteinaj** [comment]
Dette gjør vi i XSLT.

@usama49 @olavindergaard @PerSennels: har en av dere mulighet til å se på denne en gang? Jeg setter opp alle dere på denne inntil videre.

**Comment by olavindergaard** [comment]
Her er det vel tryggest å bare slette begge elementene?:   
-  <h1 class="title fulltitle">
-  <p class="docauthor author">

Og deretter slette <level1> dersom det ikke er annet innhold...

**Comment by Yazazie** [comment]
Enig med Olav, dersom <doctitle> og<h1 class="title fulltitle"> er helt like. Pass opp for undertitler som ikke alltid er tatt med i doctitle. Husker ikke om undertitlene som regel kommer etter, men også i <h1> titlepage og halftitlepage.

**Comment by olavindergaard** [comment]
Jeg har fikset dette (kun for epub-to-dtbook-audio). 
Vi sletter kun:
- <h1 class="title fulltitle">
- <p class="docauthor author">

Så det vil fremdeles ofte være undertittel, utgaveinfo, forlag etc... i <level1 class="titlepage">
