### ISSUE TITLE
Kjør alle XSpec-tester automatisk

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#50]
Kan for eksempel lages som et bash-skript eller et python-skript.

**Comment by josteinaj** [comment]
TODO: install xspec.sh

**Comment by espso** [comment]
Dette er gjort, men noen tester feiler som kanskje ikke burde gjort det? Eks. som fungerer ved test i Oxygen

Testing marcxchange-to-opf.xspec
passed: 13 / pending: 2 / failed: 37 / total: 52
XSpec test failed. See html file for details.

**Comment by josteinaj** [comment]
Sikkert noe jeg har glemt å oppdatere. :worried:
