### ISSUE TITLE
epub til dtbook: tomme mapper lages selv om konverteringen feiler

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#66]

**Comment by espso** [comment]
Har tidligere slitt med å reprodusere denne. Søkte på tomme mapper i dtbook mappene og fant 2 i DTBook, 500783 og 550268. Begge ble produsert 16. mars

**Comment by josteinaj** [comment]
Ok. Kanskje det fikset seg selv, eller det var en sjelden bug. Da lukker vi denne og satser på at ting virker?

**Comment by espso** [comment]
Kan jeg finne ut hvilke bøker 500783 og 550268 er? I så fall kan jeg ta en ekstra sjekk

**Comment by josteinaj** [comment]
Tja, de bør ligge i master/EPUB tror jeg.
