### ISSUE TITLE
Lag XSpec-tester for prepare-for-narration.xsl og lag-synkroniseringspunkter.xsl

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#69]

**Comment by PerSennels** [comment]
Skal se på det når jeg får tid. I mellomtiden har jeg fjernet noe XSLT-kode som ikke lenger var relevant, og dessuten medførte feil.

**Comment by josteinaj** [comment]
Første versjon i b996b7beb68248793afb10a7be8440c7646ef89a. Lagt til flere tester senere også.
