### ISSUE TITLE
E-post bør konfigureres i en konfigurasjonsfil

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#70]
- bør være et enkelt format å redigere. Kanskje en av disse: XML, CSV, YAML, JSON
- bør være lett tilgjengelig. Dvs. bør ligge på dokumentlageret hvor alle kan redigere den
- hva skjer med syntaksfeil i e-postfilen? sendes e-post noe sted? hvor er den e-posten isåfall definert?

**Comment by espso** [comment]
Ligger på //srvdok/dokumentlager/Fellesdokumenter/IKT/produksjonssystem.yaml

Syntaksfeil går nok ikke bra, trenger også restart av systemet for å brukes

**Comment by josteinaj** [comment]
Ideelt sett burde vi kunne oppdatere konfigurasjonen uten å måtte starte på nytt, men ikke så akutt.

Kanskje beskjed om syntaksfeil kan sendes til slack?

**Comment by josteinaj** [comment]
E-post lastes nå fra konfigurasjonsfil. Jeg lukker denne, og åpnet to nye saker om forbedringer:
- #88 
- #87
