### ISSUE TITLE
Mulighet for å automatisk trigge bøker som finnes i inn-mappa men ikke ut-mappa

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#75]
For eksempel hvis man starter systemet på nytt, eller man legger til en ny pipeline, så vil man kanskje dette.

**Comment by espso** [comment]
Dette er halvveis implementert. 

 - For å huske det, det er en bug hvis det ikke finnes noen ut mappe, men inn mappen finnes. (Hvis man setter en ny ut mappe eller noe sånt og vil trigge alle bøkene)

**Comment by josteinaj** [comment]
Ut-mappen skal lages automatisk hvis den ikke finnes tror jeg. Men kanskje den prøver å finne ut-mappen før ut-mappen blir laget?

**Comment by espso** [comment]
Den lager lydsnutter, men ikke baksidetekst osv. Parentdirs:

parentdirs = {
                  "abstracts": "Lydutdrag",
                  "back-cover": "Baksidetekst",
                  "test-audio": "Testlytt"
                  }

Ligger i make_abstracts og undermappene blir ikke laget før os.makedirs() på slutten. Legger jeg en try inn i retry_books_incoming_thread går det helt fint. Hvis vi ikke vil gjøre det sånn, må vi nok lage undermappene på et annet sted.

**Comment by josteinaj** [comment]
Aha, skjønner.

I `run.py` lages mappene:

```python
        # Make directories
        for d in self.dirs:
            os.makedirs(self.dirs[d], exist_ok=True)
```

Men kanskje undermappene heller bør lages i `pipeline.py` inni `start(...)`?

```python
    def start(self, ...):
...
        assert self.dir_in != None and ...
        assert self.dir_out != None and ...
        
        for p in self.parentdirs:
            os.makedirs(os.path.join(self.dir_out, self.parentdirs[p]), exist_ok=True)
```

Da blir mappen laget før `retry_books_incoming_thread` startes, siden den startes lenger ned i `start(...)`.

Tror du det vil funke?

**Comment by espso** [comment]
Det tror jeg vil funke helt fint, og er sikkert en bedre måte å gjøre det på

**Comment by espso** [comment]
Ja må bare passe på ytelsen osv
