### ISSUE TITLE
Rutiner for feilretting og start/omstart av produksjon

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#83]
Hvis det er en feil i katalogen som stopper produksjonen, så går det en e-post til den ansvarlige bibliotekaren.
- Hvordan vet produsenten at feilen er rettet? Skal bibliotekar sende e-post?
- Kan produsent anta at bibliotekar skal fikse katalogiseringen, eller må produsent si ifra til bibliotekar for sikkerhets skyld?
- Bør boka i det hele tatt gå videre til produsent i Quickbase før katalogposten er valid? Det er vel ikke noen annen måte å gjøre dette på? Kanskje det vil være nok å fikse #79.

Når boka skal produseres i et nytt format; kan vi sørge for at produksjon i det nye formatet starter automatisk? Eventuelt hva er rutinen for å starte produksjon på nytt manuelt? Kan vi f.eks. ha en knapp i Quickbase som starter produksjon på nytt for et gitt format? (se: #86)

Hva om vi re-produserer alt som står som til produksjon i quickbase, men ikke som "klar til utlån", hver morgen. Sånn at eventuelle feilmeldinger sendes ut på nytt og produksjonen blir produsert dersom det er skjedd feilretting i metadata.

**Comment by olavindergaard** [comment]
Jeg er litt usikker på om det er en grei løsning siden den er manuell, men bibliotekarene har nå fått beskjed om å trigge EPUB-konvertering på nytt via QuickBase etter at de har rettet opp feil i katalogen.

**Comment by josteinaj** [comment]
Litt hårete sak dette her. Tror vi bare sier at "det går seg til"...
