### ISSUE TITLE
Knapp(er) i Quickbase for å starte produksjon på nytt

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#86]
@olavindergaard lyst til å undersøke om dette er enkelt å få til? Med f.eks. Zapier eller Workato, eventuelt om det er noe innebygget i Quickbase så er det også mulig.

```
if clicked "start produksjon":
    sendSlack "nlb pipeline prodsys trigger {bookId}"
```

Vi kan isåfall enten ha én knapp som starter produksjon i alle formater på nytt, eller separate knapper for å starte produksjon i hvert enkelt format separat.

**Comment by olavindergaard** [comment]
Har gjort en webhook integrasjon mellom QuickBase og Slack slik at vi kan trigge konverteringer fra QuickBase
