### ISSUE TITLE
Send beskjed til Slack om det oppstår feil ved lesing av konfigurasjonsfil

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#87]
try / catch osv.

**Comment by espso** [comment]
Hva skal vi gjøre når yaml.load failer på grunn av syntaksfeil? Stoppe produksjonssystemet, bare fortsette eller noe annet?

**Comment by josteinaj** [comment]
- sende feilmeldingen til slack
- vente et minutt før man prøver igjen

**Comment by josteinaj** [comment]
Men akkurat det med å prøve igjen er vel mer en del av #88.
