### ISSUE TITLE
Oppdater konfigurasjon fra konfigurasjonsfil jevnlig

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#88]
Dette forutsetter enten:
- at all konfigurasjon leses fra f.eks. `Pipeline.config`
- eller at konfigurasjonen i hver Pipeline-instans oppdateres jevnlig

Det første er trolig enklere.

Lag en tråd i `run.py` som sjekker konfigurasjonsfila en gang hvert 5.minutt eller noe sånt, og prøver å oppdatere konfigurasjonen.

Ekstra fint vil være om eventuelle endringer i konfigurasjonen rapporteres på slack. F.eks. `Konfigurasjon for "Pipeline-Tittel" ble oppdatert: "{ ... }"`.

**Comment by espso** [comment]
Man må kanskje starte pipelines på nytt etter å ha oppdatert configen?

**Comment by josteinaj** [comment]
Hvis pipelines leser konfigurasjonen fra f.eks. `Pipeline.config` istedenfor å lese fra `self.email_settings["recipients"]` så tror jeg det bør gå bra. Det er vel bare e-post-adresser som lagres som konfigurasjon akkurat nå uansett.

**Comment by espso** [comment]
Dette er implementert, men uten noen rapportering om hva som er oppdatert. Litt usikker på hvordan man skal evt. få til det

**Comment by espso** [comment]
Har også implementert melding til slack, dette ser ut til å funke ok.
