### ISSUE TITLE
Når det bestilles et nytt format for en eksisterende bok i Quickbase; start produksjon av det formatet

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#92]

**Comment by olavindergaard** [comment]
Dette kan jeg trigge i Quickbase om ønskelig

**Comment by josteinaj** [comment]
Ja det fungerer vel allerede egentlig? Men vil gjerne at det skjer automatisk også.

**Comment by olavindergaard** [comment]
Da er dette på plass i skjemaregler i Quickbase.
