### ISSUE TITLE
subdir som brukes for storeBook bør være tilgjengelig som en instans-variabel

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#97]
I make_abstracts.py så lagres bøkene i undermapper: "Lydutdrag" / "Baksidetekst" / "Testlytt".

For at `_retry_books_not_in_out_thread` (se #75) skal finne bøkene i `dir_out` så må den vite at den må lete i disse undermappene. Dette kunne den visst hvis undermappene var definert som f.eks. `self.subdirs`. For eksempel:

I toppen av make_abstracts.py:
```python
subdirs = {
  "abstracts": "Lydutdrag",
  "back-cover": "Baksidetekst",
  "test-audio": "Testlytt"
}
```

I toppen av pipeline.py:
```python
subdirs = {}
```

I `_retry_books_not_in_out_thread`:
```python
if self.subdirs:
  # sjekk undermapper
else:
  # sjekk dir_out
```

**Comment by josteinaj** [comment]
Forøvrig så kunne det kanskje vært nyttig å ha et `parentdir`-argument til `storeBook`, sånn at du kunne lagret lydutdragene som dette:

```python
self.utils.filesystem.storeBook(pef_dir, identifier, parentdir=self.subdirs["abstracts"])
```

Og da kanskje `self.subdirs` burde hete `self.parentdirs`...

**Comment by espso** [comment]
Dette er nå implementert og blir brukt i retry not in out thread (som er kommentert ut). Make_abstracts lagrer nå ved bruk av storebook i stedet for shutil.copy
