### ISSUE TITLE
Test av lydutdrag

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/produksjonssystem#99]
`create-abstracts`-pipeline'en er ikke koblet sammen med resten av systemet; den er adskilt med et manuelt steg. Dermed vil den ikke trigges automatisk som alle de andre pipelines'ene gjør ved testing.

Det bør kopieres en enkel DAISY 2.02-bok til `daisy202`-mappen sånn at den blir trigget.

**Comment by espso** [comment]
Dette skal være fiksa. Antar 350 kB er ok for en liten bok. Ser ut som PEF fortsatt feiler etter en god stund for denne testboka
